import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Auto-generated sidebar from docusaurus-plugin-openapi-docs
// eslint-disable-next-line @typescript-eslint/no-var-requires
let apiSidebar: SidebarsConfig["apiSidebar"] = [];
try {
  // The sidebar file is generated by `docusaurus gen-api-docs all`
  // and may not exist on a fresh clone before the first build.
  apiSidebar =
    require("./docs/api/sidebar.ts") as SidebarsConfig["apiSidebar"];
} catch {
  // Sidebar not yet generated — will be created at build time
}

const sidebars: SidebarsConfig = {
  apiSidebar,
  userManual: [
    {
      type: "doc",
      id: "intro",
      label: "Overview",
    },
    {
      type: "category",
      label: "Part I — Getting Started",
      collapsed: false,
      items: [
        "part1-getting-started/01-introduction",
        "part1-getting-started/00a-prerequisites",
        "part1-getting-started/00b-installation",
        "part1-getting-started/00c-dataset-acquisition",
        "part1-getting-started/00-dashboard",
        "part1-getting-started/02-data-sources",
      ],
    },
    {
      type: "category",
      label: "Part II — Vocabulary",
      items: [
        "part2-vocabulary/03-vocabulary-browser",
        "part2-vocabulary/04-concept-sets",
        "part2-vocabulary/04a-mapping-assistant",
      ],
    },
    {
      type: "category",
      label: "Part III — Cohorts",
      items: [
        "part3-cohorts/05-cohort-expressions",
        "part3-cohorts/06-building-cohorts",
        "part3-cohorts/07-generating-cohorts",
        "part3-cohorts/08-cohort-management",
      ],
    },
    {
      type: "category",
      label: "Part IV — Analyses & Studies",
      items: [
        "part4-analyses/09-characterization",
        "part4-analyses/10-incidence-rates",
        "part4-analyses/11-treatment-pathways",
        "part4-analyses/12-population-level-estimation",
        "part4-analyses/13-patient-level-prediction",
        "part4-analyses/14-studies",
        "part4-analyses/14a-sccs",
        "part4-analyses/14b-evidence-synthesis",
        "part4-analyses/14c-study-designer",
        "part4-analyses/14d-study-packages",
        "part4-analyses/14e-phenotype-library",
      ],
    },
    {
      type: "category",
      label: "Part V — Data Ingestion & ETL",
      items: [
        "part5-ingestion/15-uploading-data",
        "part5-ingestion/16-schema-mapping",
        "part5-ingestion/17-concept-mapping",
        "part5-ingestion/17a-source-profiler",
        "part5-ingestion/17b-fhir-ingestion",
        "part5-ingestion/17c-etl-tools",
        "part5-ingestion/18-jobs-monitoring",
      ],
    },
    {
      type: "category",
      label: "Part VI — Data Explorer",
      items: [
        "part6-data-explorer/18-characterization-achilles",
        "part6-data-explorer/19-data-quality-dashboard",
        "part6-data-explorer/20-population-stats",
        "part6-data-explorer/20a-query-assistant",
        "part6-data-explorer/21-ares-data-observatory",
      ],
    },
    {
      type: "category",
      label: "Part VII — Patient Profiles & Care Gaps",
      items: [
        "part7-patient-profiles/21-patient-timelines",
        "part7-patient-profiles/21a-care-gaps",
      ],
    },
    {
      type: "category",
      label: "Part VIII — Administration",
      items: [
        "part8-administration/22-user-management",
        "part8-administration/23-roles-permissions",
        "part8-administration/24-authentication-providers",
        "part8-administration/25-system-configuration",
        "part8-administration/25a-system-health",
        "part8-administration/25b-ai-providers",
        "part8-administration/26-audit-log",
        "part8-administration/27-solr-administration",
        "part8-administration/28-abby-ai-assistant",
        "part8-administration/28a-vocabulary-admin",
        "part8-administration/28b-webapi-registry",
      ],
    },
    {
      type: "category",
      label: "Part IX — Genomics",
      items: [
        "part9-genomics/27-genomics-overview",
        "part9-genomics/27a-vcf-upload-annotation",
        "part9-genomics/27b-analysis-tumor-board",
      ],
    },
    {
      type: "category",
      label: "Part X — Imaging",
      items: [
        "part10-imaging/28-imaging-overview",
        "part10-imaging/28a-ohif-viewer",
        "part10-imaging/28b-timeline-response",
      ],
    },
    {
      type: "category",
      label: "Part XI — HEOR",
      items: [
        "part11-heor/29-heor-overview",
        "part11-heor/29a-claims-explorer",
        "part11-heor/29b-visualizations-contracts",
      ],
    },
    {
      type: "category",
      label: "Part XII — FHIR EHR Integration",
      items: [
        "part12-fhir/30-fhir-ehr-integration",
        "part12-fhir/30a-fhir-admin",
      ],
    },
    {
      type: "category",
      label: "Part XIII — GIS Explorer",
      items: [
        "part13-gis/31-gis-explorer",
        "part13-gis/31a-contextual-layers",
        "part13-gis/31b-spatial-analysis",
      ],
    },
    {
      type: "category",
      label: "Part XIV — Morpheus Inpatient Data",
      items: [
        "part14-morpheus/32-morpheus-overview",
        "part14-morpheus/33-morpheus-dashboard",
        "part14-morpheus/34-morpheus-patient-journey",
        "part14-morpheus/35-morpheus-datasets",
      ],
    },
    {
      type: "category",
      label: "Abby AI",
      items: [
        "abby-ai/abby-origins",
        "abby-ai/abby-architecture",
        "abby-ai/abby-knowledge-base",
        "abby-ai/abby-rag-pipeline",
        "abby-ai/abby-commons-integration",
        "abby-ai/abby-administration",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: ["architecture/database-architecture"],
    },
    {
      type: "category",
      label: "Migration Guide (Atlas → Parthenon)",
      items: [
        "migration/00-overview",
        "migration/01-before-you-begin",
        "migration/02-export-from-atlas",
        "migration/03-import-into-parthenon",
        "migration/04-validating-parity",
        "migration/05-cutover",
        "migration/06-feature-comparison",
      ],
    },
    {
      type: "category",
      label: "Appendices",
      items: [
        "appendices/a-keyboard-shortcuts",
        "appendices/b-omop-domains",
        "appendices/c-circe-json-schema",
        "appendices/d-api-quick-reference",
        "appendices/e-glossary",
        "appendices/f-known-limitations",
        "appendices/g-troubleshooting",
      ],
    },
  ],
};

export default sidebars;
