"""Tests for the credentials contract action."""
from __future__ import annotations

from pathlib import Path

from installer import contract


def _write_creds(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(0o600)


def test_credentials_action_reads_admin_password(tmp_path, monkeypatch):
    monkeypatch.setattr("installer.utils.REPO_ROOT", tmp_path)
    monkeypatch.setattr("installer.config.utils.is_port_free", lambda port: True)
    creds_path = tmp_path / ".install-credentials"
    _write_creds(
        creds_path,
        "DB_PASSWORD=db-secret\n"
        "REDIS_PASSWORD=redis-secret\n"
        "APP_KEY=base64:abc\n"
        "ADMIN_PASSWORD=Admin-XYZ-123\n",
    )

    payload = contract.build_payload(
        "credentials",
        community=True,
        overrides={"admin_email": "admin@example.com"},
    )

    assert payload == {
        "admin_email": "admin@example.com",
        "admin_password": "Admin-XYZ-123",
        "credentials_path": str(creds_path),
    }


def test_credentials_action_returns_error_when_file_missing(tmp_path, monkeypatch):
    monkeypatch.setattr("installer.utils.REPO_ROOT", tmp_path)
    monkeypatch.setattr("installer.config.utils.is_port_free", lambda port: True)

    payload = contract.build_payload(
        "credentials",
        community=True,
        overrides={"admin_email": "admin@example.com"},
    )

    assert payload == {
        "admin_email": "admin@example.com",
        "admin_password": None,
        "credentials_path": str(tmp_path / ".install-credentials"),
        "error": "credentials file not found",
    }


def test_credentials_action_ignores_blank_lines_and_comments(tmp_path, monkeypatch):
    monkeypatch.setattr("installer.utils.REPO_ROOT", tmp_path)
    monkeypatch.setattr("installer.config.utils.is_port_free", lambda port: True)
    creds_path = tmp_path / ".install-credentials"
    _write_creds(
        creds_path,
        "# generated by installer\n"
        "\n"
        "ADMIN_PASSWORD=Real-Password   \n",  # trailing whitespace before newline
    )

    payload = contract.build_payload(
        "credentials",
        community=True,
        overrides={"admin_email": "admin@example.com"},
    )

    # Trailing whitespace must be stripped from the value.
    assert payload["admin_password"] == "Real-Password"


def test_credentials_action_is_not_redacted_even_with_redact_flag(tmp_path, monkeypatch):
    monkeypatch.setattr("installer.utils.REPO_ROOT", tmp_path)
    monkeypatch.setattr("installer.config.utils.is_port_free", lambda port: True)
    creds_path = tmp_path / ".install-credentials"
    _write_creds(creds_path, "ADMIN_PASSWORD=Plain-Password\n")

    payload = contract.build_payload(
        "credentials",
        community=True,
        overrides={"admin_email": "admin@example.com"},
        redacted=True,
    )

    # Even with redacted=True, the credentials action must surface the real
    # password — that's its whole purpose. Other actions like 'defaults' would
    # still redact admin_password.
    assert payload["admin_password"] == "Plain-Password"
