slice_name: 'MIMIC v2: Unique ICU Patients'
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: COUNT(DISTINCT subject_id)
    label: Unique ICU Patients
  subheader: Distinct patients
  y_axis_format: ',d'
query_context: null
cache_timeout: null
uuid: adb98ad2-a014-5409-89f4-785600946a4b
version: 1.0.0
dataset_uuid: 3cecacd3-63d3-5a05-98e3-c5c2b905deb1
