slice_name: 'MIMIC v2: Top Services by ICU Admissions'
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  viz_type: dist_bar
  color_scheme: supersetColors
  groupby:
  - service
  metrics:
  - expressionType: SQL
    sqlExpression: COUNT(*)
    label: ICU Stays
  row_limit: 20
  show_bar_value: true
  x_axis_label: Service
  y_axis_label: ICU Stays
  order_desc: true
query_context: null
cache_timeout: null
uuid: 4973374d-946c-5448-b896-399446cb8fb7
version: 1.0.0
dataset_uuid: 3cecacd3-63d3-5a05-98e3-c5c2b905deb1
