slice_name: 'MIMIC v2: Infusion Category Total Amount'
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  viz_type: dist_bar
  color_scheme: supersetColors
  groupby:
  - category
  metrics:
  - expressionType: SQL
    sqlExpression: ROUND(SUM(total_amount)::numeric, 1)
    label: Total Amount
  row_limit: 20
  show_bar_value: true
  x_axis_label: Infusion Category
  y_axis_label: Total Amount
  order_desc: true
query_context: null
cache_timeout: null
uuid: 3b7b95fa-4db4-541f-812b-905e8f09216a
version: 1.0.0
dataset_uuid: 1a5ba3e4-beaa-5a0e-a18d-813c12dab0c4
