slice_name: 'MIMIC v2: White Blood Cells Daily Trend'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  viz_type: echarts_timeseries_line
  color_scheme: supersetColors
  groupby: []
  metrics:
  - expressionType: SIMPLE
    column:
      column_name: median_value
    aggregate: AVG
    label: Avg Daily Median Value
  row_limit: 10000
  x_axis: calendar_day
  adhoc_filters:
  - clause: WHERE
    comparator: White Blood Cells
    expressionType: SIMPLE
    operator: ==
    subject: lab_test
query_context: null
cache_timeout: null
uuid: be5a96cf-8a48-5ad0-9379-d99f46daddf3
version: 1.0.0
dataset_uuid: 41c09e96-faaf-551e-a207-5efc95f2c227
