\pset pager off
\echo 'Creating OHDSI Medical Imaging extension tables in omop'

CREATE TABLE IF NOT EXISTS omop.image_occurrence (
    image_occurrence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    visit_occurrence_id bigint,
    procedure_occurrence_id bigint NOT NULL,
    wadors_uri text,
    local_path text,
    image_occurrence_date date NOT NULL,
    image_study_uid varchar(250) NOT NULL,
    image_series_uid varchar(250) NOT NULL,
    modality_concept_id integer NOT NULL,
    anatomic_site_concept_id integer
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_image_occurrence_study_series_uid
    ON omop.image_occurrence (image_study_uid, image_series_uid);

CREATE INDEX IF NOT EXISTS idx_image_occurrence_person_date
    ON omop.image_occurrence (person_id, image_occurrence_date);

CREATE INDEX IF NOT EXISTS idx_image_occurrence_proc
    ON omop.image_occurrence (procedure_occurrence_id);

CREATE INDEX IF NOT EXISTS idx_image_occurrence_modality
    ON omop.image_occurrence (modality_concept_id);

CREATE TABLE IF NOT EXISTS omop.image_feature (
    image_feature_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    image_occurrence_id bigint NOT NULL,
    image_feature_concept_id integer NOT NULL,
    image_feature_type_concept_id integer NOT NULL,
    image_feature_event_field_concept_id integer,
    image_feature_event_id bigint,
    image_finding_concept_id integer,
    image_finding_id bigint,
    anatomic_site_concept_id integer,
    alg_system text,
    alg_datetime timestamp
);

CREATE INDEX IF NOT EXISTS idx_image_feature_occurrence
    ON omop.image_feature (image_occurrence_id);

CREATE INDEX IF NOT EXISTS idx_image_feature_person
    ON omop.image_feature (person_id);

CREATE INDEX IF NOT EXISTS idx_image_feature_concept
    ON omop.image_feature (image_feature_concept_id);

COMMENT ON TABLE omop.image_occurrence IS
    'OHDSI Medical Imaging Working Group extension table.';

COMMENT ON TABLE omop.image_feature IS
    'OHDSI Medical Imaging Working Group extension table.';
