\pset pager off
\echo 'Creating public Genomic-CDM prototype tables in omop'

CREATE TABLE IF NOT EXISTS omop.genomic_test (
    genomic_test_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_site_id bigint NOT NULL,
    genomic_test_name varchar(255),
    genomic_test_version varchar(50),
    reference_genome varchar(50),
    sequencing_device varchar(50),
    library_preparation varchar(50),
    target_capture varchar(50),
    read_type varchar(50),
    read_length integer,
    quality_control_tools varchar(255),
    total_reads integer,
    mean_target_coverage double precision,
    per_target_base_cover_100x double precision,
    alignment_tools varchar(255),
    variant_calling_tools varchar(255),
    chromosome_corrdinate varchar(255),
    annotation_tools varchar(255),
    annotation_databases varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_genomic_test_care_site
    ON omop.genomic_test (care_site_id);

CREATE TABLE IF NOT EXISTS omop.target_gene (
    target_gene_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genomic_test_id bigint NOT NULL,
    hgnc_id varchar(50) NOT NULL,
    hgnc_symbol varchar(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_target_gene_genomic_test
    ON omop.target_gene (genomic_test_id);

CREATE INDEX IF NOT EXISTS idx_target_gene_symbol
    ON omop.target_gene (hgnc_symbol);

CREATE TABLE IF NOT EXISTS omop.variant_occurrence (
    variant_occurrence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_occurrence_id bigint NOT NULL,
    specimen_id bigint NOT NULL,
    reference_specimen_id bigint,
    target_gene1_id varchar(50),
    target_gene1_symbol varchar(255),
    target_gene2_id varchar(50),
    target_gene2_symbol varchar(255),
    reference_sequence varchar(50),
    rs_id varchar(50),
    reference_allele varchar(255),
    alternate_allele varchar(255),
    hgvs_c text,
    hgvs_p text,
    variant_read_depth integer,
    variant_exon_number integer,
    copy_number double precision,
    cnv_locus text,
    fusion_breakpoint text,
    fusion_supporting_reads integer,
    sequence_alteration text,
    variant_feature text,
    genetic_origin varchar(50),
    genotype varchar(50)
);

CREATE INDEX IF NOT EXISTS idx_variant_occurrence_procedure
    ON omop.variant_occurrence (procedure_occurrence_id);

CREATE INDEX IF NOT EXISTS idx_variant_occurrence_specimen
    ON omop.variant_occurrence (specimen_id);

CREATE INDEX IF NOT EXISTS idx_variant_occurrence_gene1_symbol
    ON omop.variant_occurrence (target_gene1_symbol);

CREATE TABLE IF NOT EXISTS omop.variant_annotation (
    variant_annotation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_occurrence_id bigint NOT NULL,
    anntation_field text NOT NULL,
    value_as_string text,
    value_as_number double precision
);

CREATE INDEX IF NOT EXISTS idx_variant_annotation_occurrence
    ON omop.variant_annotation (variant_occurrence_id);

COMMENT ON TABLE omop.genomic_test IS
    'Public Genomic-CDM prototype table. Use with explicit provenance and validation.';

COMMENT ON TABLE omop.target_gene IS
    'Public Genomic-CDM prototype table.';

COMMENT ON TABLE omop.variant_occurrence IS
    'Public Genomic-CDM prototype table.';

COMMENT ON TABLE omop.variant_annotation IS
    'Public Genomic-CDM prototype table.';
