\pset pager off
\echo 'Creating GIS extension tables in omop'

CREATE TABLE IF NOT EXISTS omop.location_history (
    location_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL,
    domain_id varchar(50) NOT NULL,
    location_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date,
    relationship_type_concept_id bigint
);

CREATE INDEX IF NOT EXISTS idx_omop_location_history_entity_domain
    ON omop.location_history (entity_id, domain_id);

CREATE INDEX IF NOT EXISTS idx_omop_location_history_location
    ON omop.location_history (location_id);

CREATE INDEX IF NOT EXISTS idx_omop_location_history_dates
    ON omop.location_history (start_date, end_date);

CREATE TABLE IF NOT EXISTS omop.external_exposure (
    external_exposure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    exposure_concept_id bigint NOT NULL,
    exposure_start_date date NOT NULL,
    exposure_end_date date,
    value_as_number double precision,
    value_as_string varchar(255),
    value_as_concept_id bigint,
    unit_source_value varchar(50),
    unit_concept_id bigint,
    location_id bigint,
    boundary_id bigint,
    qualifier_concept_id bigint,
    exposure_type_concept_id bigint,
    exposure_source_concept_id bigint,
    exposure_source_value varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_omop_external_exposure_person
    ON omop.external_exposure (person_id);

CREATE INDEX IF NOT EXISTS idx_omop_external_exposure_concept
    ON omop.external_exposure (exposure_concept_id);

CREATE INDEX IF NOT EXISTS idx_omop_external_exposure_dates
    ON omop.external_exposure (exposure_start_date, exposure_end_date);

CREATE INDEX IF NOT EXISTS idx_omop_external_exposure_boundary
    ON omop.external_exposure (boundary_id);

COMMENT ON TABLE omop.location_history IS
    'OHDSI GIS extension table materialized inside omop for compliance-oriented deployment.';

COMMENT ON TABLE omop.external_exposure IS
    'OHDSI GIS extension table materialized inside omop for compliance-oriented deployment.';
