\pset pager off
\echo 'Creating additive crosswalk and mapping tables in app'

CREATE TABLE IF NOT EXISTS app.omop_extension_backfill_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extension_name varchar(50) NOT NULL,
    run_label varchar(200) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'planned',
    started_at timestamp,
    finished_at timestamp,
    notes text
);

CREATE TABLE IF NOT EXISTS app.omop_imaging_modality_map (
    source_modality varchar(20) PRIMARY KEY,
    modality_concept_id integer NOT NULL,
    notes text
);

CREATE TABLE IF NOT EXISTS app.omop_imaging_anatomic_site_map (
    source_value varchar(100) PRIMARY KEY,
    anatomic_site_concept_id integer NOT NULL,
    notes text
);

CREATE TABLE IF NOT EXISTS app.omop_imaging_feature_map (
    feature_name varchar(200) PRIMARY KEY,
    image_feature_concept_id integer NOT NULL,
    image_feature_type_concept_id integer NOT NULL,
    notes text
);

CREATE TABLE IF NOT EXISTS app.imaging_study_omop_xref (
    study_id bigint PRIMARY KEY,
    image_occurrence_id bigint UNIQUE,
    procedure_occurrence_id bigint,
    visit_occurrence_id bigint,
    modality_concept_id integer,
    anatomic_site_concept_id integer,
    backfill_run_id bigint,
    mapping_status varchar(30) NOT NULL DEFAULT 'planned',
    notes text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.imaging_feature_omop_xref (
    feature_id bigint PRIMARY KEY,
    image_feature_id bigint UNIQUE,
    image_occurrence_id bigint,
    image_feature_concept_id integer,
    image_feature_type_concept_id integer,
    image_feature_event_field_concept_id integer,
    image_feature_event_id bigint,
    backfill_run_id bigint,
    mapping_status varchar(30) NOT NULL DEFAULT 'planned',
    notes text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.omop_genomic_test_map (
    upload_id bigint PRIMARY KEY,
    genomic_test_id bigint UNIQUE,
    care_site_id bigint,
    genomic_test_name varchar(255),
    genomic_test_version varchar(50),
    reference_genome varchar(50),
    sequencing_device varchar(50),
    library_preparation varchar(50),
    target_capture varchar(50),
    read_type varchar(50),
    read_length integer,
    quality_control_tools varchar(255),
    total_reads integer,
    mean_target_coverage double precision,
    per_target_base_cover_100x double precision,
    alignment_tools varchar(255),
    variant_calling_tools varchar(255),
    chromosome_corrdinate varchar(255),
    annotation_tools varchar(255),
    annotation_databases varchar(255),
    backfill_run_id bigint,
    mapping_status varchar(30) NOT NULL DEFAULT 'planned',
    notes text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.omop_gene_symbol_map (
    gene_symbol varchar(100) PRIMARY KEY,
    hgnc_id varchar(50) NOT NULL,
    hgnc_symbol varchar(50) NOT NULL,
    notes text
);

CREATE TABLE IF NOT EXISTS app.genomic_variant_omop_xref (
    variant_id bigint PRIMARY KEY,
    variant_occurrence_id bigint UNIQUE,
    procedure_occurrence_id bigint,
    specimen_id bigint,
    reference_specimen_id bigint,
    target_gene1_id varchar(50),
    target_gene1_symbol varchar(255),
    target_gene2_id varchar(50),
    target_gene2_symbol varchar(255),
    backfill_run_id bigint,
    mapping_status varchar(30) NOT NULL DEFAULT 'planned',
    notes text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE app.imaging_study_omop_xref IS
    'Non-destructive mapping table from app.imaging_studies to omop.image_occurrence.';

COMMENT ON TABLE app.imaging_feature_omop_xref IS
    'Non-destructive mapping table from app.imaging_features to omop.image_feature.';

COMMENT ON TABLE app.omop_genomic_test_map IS
    'Curated assay-level mapping table used to materialize omop.genomic_test from app.genomic_uploads.';

COMMENT ON TABLE app.genomic_variant_omop_xref IS
    'Non-destructive mapping table from app.genomic_variants to omop.variant_occurrence.';

\echo 'Series-level imaging bridge is created by 021_imaging_series_bridge.sql'

/*
Run scripts/omop-extension-package/021_imaging_series_bridge.sql before any
series-granular imaging backfill. MI-CDM image_occurrence rows are study+series
grain, so a study-level xref alone is not lossless.
*/

\echo 'Optional: seed xref placeholders only when you are ready to backfill'

/*
INSERT INTO app.imaging_study_omop_xref (study_id)
SELECT s.id
FROM app.imaging_studies s
WHERE NOT EXISTS (
    SELECT 1
    FROM app.imaging_study_omop_xref x
    WHERE x.study_id = s.id
);

INSERT INTO app.imaging_feature_omop_xref (feature_id)
SELECT f.id
FROM app.imaging_features f
WHERE NOT EXISTS (
    SELECT 1
    FROM app.imaging_feature_omop_xref x
    WHERE x.feature_id = f.id
);

INSERT INTO app.omop_genomic_test_map (upload_id)
SELECT u.id
FROM app.genomic_uploads u
WHERE NOT EXISTS (
    SELECT 1
    FROM app.omop_genomic_test_map m
    WHERE m.upload_id = u.id
);

INSERT INTO app.genomic_variant_omop_xref (variant_id)
SELECT v.id
FROM app.genomic_variants v
WHERE NOT EXISTS (
    SELECT 1
    FROM app.genomic_variant_omop_xref x
    WHERE x.variant_id = v.id
);
*/

\echo 'Template: imaging backfill after curation tables are populated'

/*
INSERT INTO omop.image_occurrence (
    person_id,
    visit_occurrence_id,
    procedure_occurrence_id,
    wadors_uri,
    local_path,
    image_occurrence_date,
    image_study_uid,
    image_series_uid,
    modality_concept_id,
    anatomic_site_concept_id
)
SELECT
    s.person_id,
    x.visit_occurrence_id,
    x.procedure_occurrence_id,
    s.wadors_uri,
    s.file_dir,
    s.study_date,
    s.study_instance_uid,
    sr.series_instance_uid,
    x.modality_concept_id,
    x.anatomic_site_concept_id
FROM app.imaging_studies s
JOIN app.imaging_series sr ON sr.study_id = s.id
JOIN app.imaging_study_omop_xref x ON x.study_id = s.id
WHERE x.image_occurrence_id IS NULL
  AND s.person_id IS NOT NULL
  AND x.procedure_occurrence_id IS NOT NULL
  AND x.modality_concept_id IS NOT NULL;
*/

\echo 'Template: genomic_test backfill after assay metadata curation'

/*
INSERT INTO omop.genomic_test (
    care_site_id,
    genomic_test_name,
    genomic_test_version,
    reference_genome,
    sequencing_device,
    library_preparation,
    target_capture,
    read_type,
    read_length,
    quality_control_tools,
    total_reads,
    mean_target_coverage,
    per_target_base_cover_100x,
    alignment_tools,
    variant_calling_tools,
    chromosome_corrdinate,
    annotation_tools,
    annotation_databases
)
SELECT
    m.care_site_id,
    m.genomic_test_name,
    m.genomic_test_version,
    m.reference_genome,
    m.sequencing_device,
    m.library_preparation,
    m.target_capture,
    m.read_type,
    m.read_length,
    m.quality_control_tools,
    m.total_reads,
    m.mean_target_coverage,
    m.per_target_base_cover_100x,
    m.alignment_tools,
    m.variant_calling_tools,
    m.chromosome_corrdinate,
    m.annotation_tools,
    m.annotation_databases
FROM app.omop_genomic_test_map m
WHERE m.genomic_test_id IS NULL
  AND m.care_site_id IS NOT NULL;
*/

\echo 'Template: variant_occurrence backfill after specimen/procedure mapping'

/*
INSERT INTO omop.variant_occurrence (
    procedure_occurrence_id,
    specimen_id,
    reference_specimen_id,
    target_gene1_id,
    target_gene1_symbol,
    target_gene2_id,
    target_gene2_symbol,
    reference_sequence,
    rs_id,
    reference_allele,
    alternate_allele,
    hgvs_c,
    hgvs_p,
    variant_read_depth,
    sequence_alteration,
    variant_feature,
    genetic_origin,
    genotype
)
SELECT
    x.procedure_occurrence_id,
    x.specimen_id,
    x.reference_specimen_id,
    x.target_gene1_id,
    x.target_gene1_symbol,
    x.target_gene2_id,
    x.target_gene2_symbol,
    NULL,
    NULL,
    v.reference_allele,
    v.alternate_allele,
    v.hgvs_c,
    v.hgvs_p,
    v.read_depth,
    v.variant_type,
    COALESCE(v.variant_class, v.consequence),
    CASE
        WHEN lower(v.sample_id) LIKE '%germ%' THEN 'germline'
        WHEN lower(v.sample_id) LIKE '%normal%' THEN 'germline'
        ELSE 'somatic'
    END,
    v.zygosity
FROM app.genomic_variants v
JOIN app.genomic_variant_omop_xref x ON x.variant_id = v.id
WHERE x.variant_occurrence_id IS NULL
  AND x.procedure_occurrence_id IS NOT NULL
  AND x.specimen_id IS NOT NULL;
*/

\echo 'Template: GIS backfill'

/*
INSERT INTO omop.location_history (
    entity_id,
    domain_id,
    location_id,
    start_date,
    end_date,
    relationship_type_concept_id
)
SELECT
    entity_id,
    domain_id,
    location_id,
    start_date,
    end_date,
    relationship_type_concept_id
FROM app.location_history;

INSERT INTO omop.external_exposure (
    person_id,
    exposure_concept_id,
    exposure_start_date,
    exposure_end_date,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_source_value,
    unit_concept_id,
    location_id,
    boundary_id,
    qualifier_concept_id,
    exposure_type_concept_id,
    exposure_source_concept_id,
    exposure_source_value
)
SELECT
    person_id,
    exposure_concept_id,
    exposure_start_date,
    exposure_end_date,
    value_as_number,
    value_as_string,
    value_as_concept_id,
    unit_source_value,
    unit_concept_id,
    location_id,
    boundary_id,
    qualifier_concept_id,
    exposure_type_concept_id,
    exposure_source_concept_id,
    exposure_source_value
FROM app.external_exposure;
*/
