
http:
  routers:

    traefik-dashboard:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: api@internal
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/api`, `/dashboard`)'

    traefik:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "traefik"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`)'

    broadsea-content:
     entryPoints: '{{ env "HTTP_TYPE" }}'
     service: "broadsea-content"
     rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/`)'
      
    ohdsi-atlas:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-atlas"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/atlas`)'

    ohdsi-webapi:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-webapi"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/WebAPI`)'

    broadsea-hades:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-hades"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/hades`)'
      middlewares:
        - "broadsea-hades-root-path-header"
        - "broadsea-hades-path-strip"

    broadsea-solr-vocab:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-solr-vocab"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/solr`)'

    broadsea-ares:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-ares"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/ares`)'

    broadsea-open-shiny-server:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-open-shiny-server"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/shiny`)'
      middlewares: 
        - "broadsea-open-shiny-server-path-strip"

    broadsea-posit-connect:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-posit-connect"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/connect`)'

    broadsea-posit-api:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-posit-connect"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/__`)'

    perseus-user:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-user"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/user`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"

    perseus-backend:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-backend"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/backend`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"
        - "broadsea-backend-header"

    perseus-white-rabbit:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-white-rabbit"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/white-rabbit`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"

    perseus-cdm-builder:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-cdm-builder"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/cdm-builder`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"

    perseus-data-quality-dashboard:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-data-quality-dashboard"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/cdm-builder`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"

    perseus-athena:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-athena"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/athena`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"


    perseus-solr:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-solr"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus/solr`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"

    perseus-frontend:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "perseus-frontend"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/perseus`)'
      middlewares:
        - "broadsea-perseus-strip-prefix"


    broadsea-jupyter-notebook:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-jupyter-notebook"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/jupyter`)'


    broadsea-pgadmin4:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-pgadmin4"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/pgadmin4`)'


  middlewares:

    broadsea-backend-header:
      headers:
        customRequestHeaders:
          Username: "username"

    broadsea-hades-path-strip:
      stripPrefix:
        prefixes: 
          - "/hades"
        forceSlash: false

    broadsea-perseus-strip-prefix:
      stripPrefix:
        prefixes: 
          - "/perseus"
        forceSlash: false

    broadsea-hades-root-path-header:
      headers:
        customRequestHeaders:
          X-RStudio-Root-Path: "/hades"

    broadsea-open-shiny-server-path-strip:
      stripPrefix:
        prefixes: 
          - "/shiny"
        forceSlash: false

  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik

    broadsea-content:
      loadBalancer:
        servers:
          - url: http://broadsea-content

    ohdsi-atlas:
      loadBalancer:
        servers:
          - url: http://ohdsi-atlas:8080

    ohdsi-webapi:
      loadBalancer:
        servers:
          - url: http://ohdsi-webapi:8080

    broadsea-hades:
      loadBalancer:
        servers:
          - url: http://broadsea-hades:8787

    broadsea-solr-vocab:
      loadBalancer:
        servers:
          - url: http://broadsea-solr-vocab:8983

    broadsea-ares:
      loadBalancer:
        servers:
          - url: http://broadsea-ares

    broadsea-open-shiny-server:
      loadBalancer:
        servers:
          - url: http://broadsea-open-shiny-server:3838

    broadsea-posit-connect:
      loadBalancer:
        servers:
          - url: http://broadsea-posit-connect:3939

    perseus-backend:
      loadBalancer:
        servers:
          - url: http://perseus-backend:5004

    perseus-cdm-builder:
      loadBalancer:
        servers:
          - url: http://perseus-cdm-builder:9000

    perseus-frontend:
      loadBalancer:
        servers:
          - url: http://perseus-frontend:4200
  
    perseus-solr:
      loadBalancer:
        servers:
          - url: http://perseus-solr:8983

    perseus-usagi:
      loadBalancer:
        servers:
          - url: http://perseus-usagi:5003

    perseus-data-quality-dashboard:
      loadBalancer:
        servers:
          - url: http://perseus-data-quality-dashboard:8001

    perseus-white-rabbit:
      loadBalancer:
        servers:
          - url: http://perseus-white-rabbit:8000

    perseus-swagger:
      loadBalancer:
        servers:
          - url: http://perseus-swagger:8080

    perseus-user:
      loadBalancer:
        servers:
          - url: http://perseus-user:5001

    perseus-athena:
      loadBalancer:
        servers:
          - url: http://perseus-athena:5002

    broadsea-jupyter-notebook:
      loadBalancer:
        servers:
          - url: http://broadsea-jupyter-notebook:8888

    broadsea-pgadmin4:
      loadBalancer:
        servers:
          - url: http://broadsea-pgadmin4