# installer/generator.py
"""Generate customized acropolis.sh for day-2 operations."""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from rich.console import Console

from acropolis.installer.utils import REPO_ROOT


def generate_acropolis_sh(
    *,
    tier: str,
    domain: str,
    topology_mode: str,
    services: list[str],
    parthenon_path: Optional[str] = None,
    parthenon_url: Optional[str] = None,
    parthenon_network: Optional[str] = None,
) -> str:
    """Generate a customized acropolis.sh script."""

    # Build compose file flags
    compose_files = '-f docker-compose.yml'
    if tier in ("community", "enterprise"):
        compose_files += ' -f docker-compose.community.yml'
    if tier == "enterprise":
        compose_files += ' -f docker-compose.enterprise.yml'

    service_list = " ".join(f'"{s}"' for s in services) if services else ""

    return f'''#!/usr/bin/env bash
# =============================================================================
# Acropolis CLI — Generated by Installer
# =============================================================================
# Edition: {tier}
# Domain:  {domain}
# Topology: {topology_mode}
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Configuration (embedded by installer) ────────────────────────────────────
EDITION="{tier}"
DOMAIN="{domain}"
PARTHENON_MODE="{topology_mode}"
PARTHENON_PATH="{parthenon_path or ""}"
PARTHENON_URL="{parthenon_url or ""}"
PARTHENON_NETWORK="{parthenon_network or "parthenon"}"
NETWORK_NAME="acropolis_network"
COMPOSE_FILES=({compose_files})
SERVICES=({service_list})

# Load .env overrides
if [[ -f .env ]]; then
    set -a; source .env; set +a
fi

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
CYAN='\\033[0;36m'
NC='\\033[0m'

log_info()  {{ echo -e "${{BLUE}}[acropolis]${{NC}} $*"; }}
log_ok()    {{ echo -e "${{GREEN}}[acropolis]${{NC}} $*"; }}
log_warn()  {{ echo -e "${{YELLOW}}[acropolis]${{NC}} $*"; }}
log_error() {{ echo -e "${{RED}}[acropolis]${{NC}} $*"; }}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_up() {{
    if ! docker network inspect "$NETWORK_NAME" &>/dev/null; then
        log_info "Creating network: $NETWORK_NAME"
        docker network create "$NETWORK_NAME"
    fi
    log_info "Starting Acropolis (${{CYAN}}$EDITION${{NC}} edition)..."
    docker compose "${{COMPOSE_FILES[@]}}" up -d
    echo
    log_ok "Acropolis is running!"
    echo
    cmd_urls
}}

cmd_down() {{
    log_info "Stopping Acropolis..."
    docker compose "${{COMPOSE_FILES[@]}}" down
    log_ok "Acropolis stopped."
}}

cmd_status() {{
    echo -e "${{CYAN}}═══════════════════════════════════════════════════════════${{NC}}"
    echo -e "${{CYAN}}  Acropolis Platform Status${{NC}}"
    echo -e "${{CYAN}}═══════════════════════════════════════════════════════════${{NC}}"
    echo
    docker compose "${{COMPOSE_FILES[@]}}" ps --format 'table {{{{.Name}}}}\\t{{{{.Status}}}}\\t{{{{.Ports}}}}' 2>/dev/null || true
    echo
    echo -e "${{BLUE}}Edition:${{NC}}  $EDITION"
    echo -e "${{BLUE}}Domain:${{NC}}   $DOMAIN"
    echo -e "${{BLUE}}Topology:${{NC}} $PARTHENON_MODE"
}}

cmd_logs() {{
    local service="${{1:-}}"
    if [[ -n "$service" ]]; then
        docker compose "${{COMPOSE_FILES[@]}}" logs -f "$service"
    else
        docker compose "${{COMPOSE_FILES[@]}}" logs -f --tail=100
    fi
}}

cmd_urls() {{
    echo -e "${{CYAN}}Infrastructure:${{NC}}"
    echo -e "  Traefik Dashboard  ${{GREEN}}https://$DOMAIN:8090${{NC}}"

    echo
    echo -e "${{CYAN}}Community Services:${{NC}}"
    echo -e "  Portainer          ${{GREEN}}https://portainer.$DOMAIN${{NC}}"
    echo -e "  pgAdmin            ${{GREEN}}https://pgadmin.$DOMAIN${{NC}}"

    if [[ "$EDITION" == "enterprise" ]]; then
        echo
        echo -e "${{CYAN}}Enterprise Services:${{NC}}"
        echo -e "  n8n                ${{GREEN}}https://n8n.$DOMAIN${{NC}}"
        echo -e "  Superset           ${{GREEN}}https://superset.$DOMAIN${{NC}}"
        echo -e "  DataHub            ${{GREEN}}https://datahub.$DOMAIN${{NC}}"
        echo -e "  Authentik          ${{GREEN}}https://auth.$DOMAIN${{NC}}"
        echo -e "  Wazuh              ${{GREEN}}https://wazuh.$DOMAIN${{NC}}"
    fi

    if [[ "$PARTHENON_MODE" != "standalone" ]]; then
        echo
        echo -e "${{CYAN}}Parthenon:${{NC}}"
        echo -e "  Application        ${{GREEN}}https://parthenon.$DOMAIN${{NC}}"
        for svc in "${{SERVICES[@]}}"; do
            echo -e "  $svc               ${{GREEN}}https://$svc.$DOMAIN${{NC}}"
        done
    fi
}}

cmd_backup() {{
    local backup_dir="backups/$(date +%Y-%m-%d)"
    mkdir -p "$backup_dir"
    log_info "Backing up to $backup_dir..."

    # Backup config files
    cp -f .env "$backup_dir/" 2>/dev/null || true
    cp -f .install-credentials "$backup_dir/" 2>/dev/null || true
    cp -rf traefik/dynamic "$backup_dir/traefik-dynamic" 2>/dev/null || true

    # Backup Docker volumes
    local volumes
    volumes=$(docker compose "${{COMPOSE_FILES[@]}}" config --volumes 2>/dev/null || true)
    for vol in $volumes; do
        local full_vol
        full_vol=$(docker volume ls --format '{{{{.Name}}}}' | grep "$vol" | head -1)
        if [[ -n "$full_vol" ]]; then
            log_info "  Backing up $full_vol..."
            docker run --rm -v "$full_vol":/data -v "$(pwd)/$backup_dir":/backup \\
                alpine tar czf "/backup/${{vol}}.tar.gz" /data 2>/dev/null || true
        fi
    done

    log_ok "Backup complete: $backup_dir"
}}

cmd_smoke_test() {{
    log_info "Running smoke tests..."
    if [[ -f tests/smoke-test.sh ]]; then
        bash tests/smoke-test.sh
    else
        log_error "No smoke test found at tests/smoke-test.sh"
        exit 1
    fi
}}

cmd_update() {{
    log_info "Upgrading Acropolis + Parthenon..."
    if [[ -f "$PARTHENON_PATH/install.py" ]]; then
        python3 "$PARTHENON_PATH/install.py" --with-infrastructure --upgrade
    else
        log_info "Pulling latest images..."
        docker compose "${{COMPOSE_FILES[@]}}" pull
        log_info "Restarting services..."
        docker compose "${{COMPOSE_FILES[@]}}" up -d
        log_ok "Update complete."
    fi
}}

cmd_reconfigure() {{
    log_info "Launching installer for reconfiguration..."
    python3 install.py
}}

cmd_help() {{
    echo -e "${{CYAN}}Acropolis — Enterprise Foundation for Parthenon${{NC}}"
    echo
    echo "Usage: ./acropolis.sh <command> [options]"
    echo
    echo "Commands:"
    echo "  up              Start all services"
    echo "  down            Stop all services"
    echo "  status          Show service status"
    echo "  logs [service]  Follow logs (all or specific)"
    echo "  urls            Show service URLs"
    echo "  backup          Backup volumes and config"
    echo "  smoke-test      Run health checks"
    echo "  update          Pull latest images and restart"
    echo "  reconfigure     Re-run installer"
    echo "  help            Show this help"
}}

# ── Main ─────────────────────────────────────────────────────────────────────
case "${{1:-help}}" in
    up)         cmd_up ;;
    down)       cmd_down ;;
    status)     cmd_status ;;
    logs)       shift; cmd_logs "$@" ;;
    urls)       cmd_urls ;;
    backup)     cmd_backup ;;
    smoke-test) cmd_smoke_test ;;
    update)     cmd_update ;;
    reconfigure) cmd_reconfigure ;;
    help|--help|-h) cmd_help ;;
    *)
        log_error "Unknown command: $1"
        cmd_help
        exit 1
        ;;
esac
'''


def write_acropolis_sh(
    *,
    tier: str,
    domain: str,
    topology_mode: str,
    services: list[str],
    parthenon_path: Optional[str] = None,
    parthenon_url: Optional[str] = None,
    parthenon_network: Optional[str] = None,
    console: Console,
) -> None:
    """Generate and write the customized acropolis.sh."""
    script = generate_acropolis_sh(
        tier=tier,
        domain=domain,
        topology_mode=topology_mode,
        services=services,
        parthenon_path=parthenon_path,
        parthenon_url=parthenon_url,
        parthenon_network=parthenon_network,
    )

    path = REPO_ROOT / "acropolis.sh"
    path.write_text(script)
    os.chmod(path, 0o755)
    console.print(f"[green]Generated {path.relative_to(REPO_ROOT)} (chmod 755)[/]")
