# installer/routing.py
"""Phase 8: Traefik dynamic config generation."""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from rich.console import Console

from acropolis.installer.discovery import DiscoveredService
from acropolis.installer.utils import REPO_ROOT


DYNAMIC_DIR = REPO_ROOT / "traefik" / "dynamic"


def _router_block(
    router_name: str,
    subdomain: str,
    domain: str,
    service_name: str,
    tls_mode: str,
    *,
    middlewares: Optional[list[str]] = None,
) -> list[str]:
    """Generate a router block, respecting TLS mode."""
    entrypoint = "web" if tls_mode == "none" else "websecure"
    lines = [
        f"    {router_name}:",
        f'      rule: "Host(`{subdomain}.{domain}`)"',
        "      entryPoints:",
        f"        - {entrypoint}",
        f"      service: {service_name}",
    ]
    if tls_mode != "none":
        lines.extend([
            "      tls:",
            "        certResolver: letsencrypt",
        ])
    if middlewares:
        lines.append("      middlewares:")
        for mw in middlewares:
            lines.append(f"        - {mw}")
    return lines


def generate_parthenon_routes(
    services: list[DiscoveredService],
    domain: str,
    topology_mode: str,
    tls_mode: str = "letsencrypt",
    *,
    remote_url: Optional[str] = None,
) -> str:
    """Generate Traefik YAML for Parthenon services."""
    exposed = [s for s in services if s.expose]
    if not exposed:
        return "# No Parthenon services to route\n"

    lines = [
        "# Generated by Acropolis Installer — Parthenon Routes",
        f"# TLS mode: {tls_mode}",
        "http:",
        "  routers:",
    ]

    for svc in exposed:
        router_name = f"parthenon-{svc.subdomain}".replace(".", "-")
        lines.extend(_router_block(
            router_name, svc.subdomain, domain, router_name, tls_mode,
        ))

        # WebSocket support for reverb
        if svc.name == "reverb":
            lines.extend(_router_block(
                f"{router_name}-ws", svc.subdomain, domain, router_name, tls_mode,
                middlewares=["websocket-headers"],
            ))

    lines.extend(["", "  services:"])

    for svc in exposed:
        router_name = f"parthenon-{svc.subdomain}".replace(".", "-")
        if topology_mode == "remote" and remote_url:
            backend_url = remote_url
        else:
            backend_url = f"http://{svc.host}:{svc.port}"

        lines.extend([
            f"    {router_name}:",
            "      loadBalancer:",
            "        servers:",
            f'          - url: "{backend_url}"',
        ])

    # Add WebSocket middleware if reverb is exposed
    if any(s.name == "reverb" for s in exposed):
        lines.extend([
            "",
            "  middlewares:",
            "    websocket-headers:",
            "      headers:",
            "        customRequestHeaders:",
            '          Connection: "upgrade"',
            '          Upgrade: "websocket"',
        ])

    # Add serversTransport for Portainer self-signed cert
    lines.extend([
        "",
        "  serversTransports:",
        "    insecureTransport:",
        "      insecureSkipVerify: true",
    ])

    return "\n".join(lines) + "\n"


def generate_acropolis_routes(domain: str, tier: str) -> str:
    """Generate Traefik YAML for Acropolis's own services.

    Note: Most Acropolis services use Docker labels for routing.
    This file handles any additional routing that labels can't cover.
    """
    lines = [
        "# Generated by Acropolis Installer — Acropolis Routes",
        "# Most routing is handled via Docker labels in docker-compose files.",
        "# This file provides supplemental routing configuration.",
        "",
    ]

    return "\n".join(lines) + "\n"


def generate_traefik_static(tls_mode: str, acme_email: str) -> str:
    """Generate traefik.yml static config based on TLS mode."""
    lines = [
        "# Generated by Acropolis Installer",
        f"# TLS mode: {tls_mode}",
        "",
        "api:",
        "  dashboard: true",
        "  insecure: true",
        "",
        "ping:",
        "  entryPoint: web",
        "",
        "log:",
        "  level: INFO",
        "",
        "entryPoints:",
        "  web:",
        '    address: ":80"',
    ]

    if tls_mode != "none":
        # HTTP → HTTPS redirect
        lines.extend([
            "    http:",
            "      redirections:",
            "        entryPoint:",
            "          to: websecure",
            "          scheme: https",
            "          permanent: true",
            "",
            "  websecure:",
            '    address: ":443"',
            "    http:",
            "      tls:",
            "        certResolver: letsencrypt",
        ])

    if tls_mode == "letsencrypt":
        lines.extend([
            "",
            "certificatesResolvers:",
            "  letsencrypt:",
            "    acme:",
            f"      email: {acme_email}",
            "      storage: /etc/traefik/acme/acme.json",
            "      httpChallenge:",
            "        entryPoint: web",
        ])

    lines.extend([
        "",
        "providers:",
        "  docker:",
        "    endpoint: unix:///var/run/docker.sock",
        "    exposedByDefault: false",
        "    network: acropolis_network",
        "    watch: true",
        "",
        "  file:",
        "    directory: /etc/traefik/dynamic",
        "    watch: true",
        "",
        "serversTransport:",
        "  insecureSkipVerify: false",
    ])

    return "\n".join(lines) + "\n"


def write_route_configs(
    services: list[DiscoveredService],
    domain: str,
    topology_mode: str,
    tier: str,
    tls_mode: str,
    acme_email: str,
    console: Console,
    *,
    remote_url: Optional[str] = None,
) -> None:
    """Phase 8: Generate and write Traefik route configurations."""
    console.print("\n[bold cyan]Phase 8: Traefik Routing[/]\n")

    DYNAMIC_DIR.mkdir(parents=True, exist_ok=True)

    # Generate Traefik static config
    traefik_yml = generate_traefik_static(tls_mode, acme_email)
    traefik_path = REPO_ROOT / "traefik" / "traefik.yml"
    traefik_path.write_text(traefik_yml)
    console.print(f"[green]Wrote traefik/traefik.yml (TLS: {tls_mode})[/]")

    # Generate Parthenon routes
    if services:
        parthenon_yaml = generate_parthenon_routes(
            services, domain, topology_mode, tls_mode, remote_url=remote_url
        )
        parthenon_path = DYNAMIC_DIR / "parthenon.yml"
        parthenon_path.write_text(parthenon_yaml)
        console.print(f"[green]Wrote {parthenon_path.relative_to(REPO_ROOT)}[/]")

    # Generate Acropolis routes (supplemental)
    acropolis_yaml = generate_acropolis_routes(domain, tier)
    acropolis_path = DYNAMIC_DIR / "acropolis.yml"
    acropolis_path.write_text(acropolis_yaml)
    console.print(f"[green]Wrote {acropolis_path.relative_to(REPO_ROOT)}[/]")

    exposed_count = len([s for s in services if s.expose])
    console.print(f"[green]Routing configured for {exposed_count} Parthenon services.[/]")
