BEGIN;
CREATE SCHEMA IF NOT EXISTS omop;
ALTER TABLE inpatient.concept SET SCHEMA omop;
ALTER TABLE inpatient.concept_ancestor SET SCHEMA omop;
ALTER TABLE inpatient.concept_class SET SCHEMA omop;
ALTER TABLE inpatient.concept_relationship SET SCHEMA omop;
ALTER TABLE inpatient.concept_synonym SET SCHEMA omop;
ALTER TABLE inpatient.domain SET SCHEMA omop;
ALTER TABLE inpatient.drug_strength SET SCHEMA omop;
ALTER TABLE inpatient.relationship SET SCHEMA omop;
ALTER TABLE inpatient.source_to_concept_map SET SCHEMA omop;
ALTER TABLE inpatient.vocabulary SET SCHEMA omop;
COMMIT;
