apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acropolis

resources:
  - ../base
  # Community services deployed via Helm chart with community values
  # kubectl apply -k k8s/kustomize/community/

commonLabels:
  acropolis.io/edition: community
