<?php

namespace App\Services\Etl;

use App\Models\App\EtlProject;

class EtlDocumentService
{
    /**
     * Generate Markdown ETL specification.
     */
    public function generateMarkdown(EtlProject $project): string
    {
        $project->load(['tableMappings.fieldMappings', 'source', 'scanProfile']);

        $md = "# ETL Specification: {$project->name}\n\n";
        $md .= '**Generated:** '.now()->toIso8601String()."\n";
        $md .= "**CDM Version:** {$project->cdm_version}\n";
        $md .= "**Status:** {$project->status}\n";
        if ($project->source) {
            $md .= "**Source:** {$project->source->source_name}\n";
        }
        $md .= "\n---\n\n";

        // Summary table
        $md .= "## Mapping Summary\n\n";
        $md .= "| Source Table | CDM Table | Fields Mapped | Status |\n";
        $md .= "|---|---|---|---|\n";

        foreach ($project->tableMappings as $mapping) {
            $fieldCount = $mapping->fieldMappings->count();
            $status = $mapping->is_completed ? 'Complete' : 'In Progress';
            $stem = $mapping->is_stem ? ' (via stem)' : '';
            $md .= "| {$mapping->source_table} | {$mapping->target_table}{$stem} | {$fieldCount} | {$status} |\n";
        }
        $md .= "\n";

        // Per-table sections
        foreach ($project->tableMappings as $mapping) {
            $md .= "## {$mapping->source_table} → {$mapping->target_table}\n\n";

            if ($mapping->logic) {
                $md .= "> {$mapping->logic}\n\n";
            }

            if ($mapping->fieldMappings->isEmpty()) {
                $md .= "*No field mappings defined.*\n\n";

                continue;
            }

            $md .= "| CDM Column | Required | Source Column | Type | Logic |\n";
            $md .= "|---|---|---|---|---|\n";

            foreach ($mapping->fieldMappings as $field) {
                $req = $field->is_required ? '**Yes**' : 'No';
                $source = $field->source_column ?? '—';
                $logic = $field->logic ? str_replace('|', '\\|', $field->logic) : '—';
                $ai = $field->is_ai_suggested ? ' (AI)' : '';
                $reviewed = $field->is_reviewed ? ' ✓' : '';
                $md .= "| {$field->target_column} | {$req} | {$source}{$ai} | {$field->mapping_type} | {$logic}{$reviewed} |\n";
            }
            $md .= "\n";
        }

        // Notes
        if ($project->notes) {
            $md .= "## Notes\n\n{$project->notes}\n\n";
        }

        $md .= "---\n\n*Generated by Aqueduct ETL Mapping Designer — Parthenon*\n";

        return $md;
    }
}
