<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: 'Helvetica', sans-serif; color: #1a1a1a; margin: 40px; font-size: 11pt; line-height: 1.6; }
  h1 { font-family: Georgia, serif; font-size: 24pt; border-bottom: 2px solid #9B1B30; padding-bottom: 8px; }
  h2 { font-family: Georgia, serif; font-size: 16pt; color: #9B1B30; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  .meta { color: #666; font-size: 9pt; margin-bottom: 20px; }
  .key-finding { border-left: 3px solid #C9A227; padding-left: 12px; margin: 10px 0; background: #fefdf5; }
  .finding { border: 1px solid #ddd; border-radius: 4px; padding: 10px; margin: 8px 0; }
  .finding-type { display: inline-block; background: #f0f0f0; border-radius: 3px; padding: 2px 6px; font-size: 9pt; color: #666; }
  .narrative { font-style: italic; color: #444; margin: 8px 0; }
  .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 8pt; color: #999; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; font-size: 10pt; }
  th { background: #f5f5f5; font-weight: 600; }
</style>
</head>
<body>
  <h1>{{ $meta['title'] }}</h1>
  <div class="meta">
    @if($meta['research_question'])<p><strong>Research Question:</strong> {{ $meta['research_question'] }}</p>@endif
    <p>Status: {{ ucfirst($meta['status']) }} &middot; Owner: {{ $meta['owner'] ?? 'Unknown' }} &middot; Exported: {{ $meta['exported_at'] }}</p>
  </div>

  @if(count($key_findings) > 0)
  <h2>Key Findings</h2>
  @foreach($key_findings as $kf)
  <div class="key-finding">
    <span class="finding-type">{{ str_replace('_', ' ', $kf['finding_type']) }}</span>
    @foreach($kf['finding_payload'] as $k => $v)
      <br><strong>{{ str_replace('_', ' ', $k) }}:</strong> {{ is_array($v) ? implode(', ', $v) : $v }}
    @endforeach
  </div>
  @endforeach
  @endif

  @foreach($sections as $sectionKey => $section)
  <h2>{{ str_replace('_', ' ', ucfirst($sectionKey)) }}</h2>
  @if($section['narrative'])<div class="narrative">{{ $section['narrative'] }}</div>@endif
  @forelse($section['pins'] as $pin)
  <div class="finding @if($pin['is_key_finding']) key-finding @endif">
    <span class="finding-type">{{ str_replace('_', ' ', $pin['finding_type']) }}</span>
    @if($pin['narrative_before'])<div class="narrative">{{ $pin['narrative_before'] }}</div>@endif
    @foreach($pin['finding_payload'] as $k => $v)
      <br><strong>{{ str_replace('_', ' ', $k) }}:</strong> {{ is_array($v) ? implode(', ', $v) : $v }}
    @endforeach
    @if($pin['narrative_after'])<div class="narrative">{{ $pin['narrative_after'] }}</div>@endif
  </div>
  @empty
  <p style="color: #999;">No findings in this section.</p>
  @endforelse
  @endforeach

  <div class="footer">
    Generated by Parthenon Evidence Investigation Platform &middot; {{ $meta['exported_at'] }} &middot; Version {{ $meta['version'] }}
  </div>
</body>
</html>
