#!/usr/bin/env bash
# fix-issue.sh — Use Claude Code to fix a GitHub issue
#
# Usage: ./scripts/claude-agents/fix-issue.sh <issue-number>
# Example: ./scripts/claude-agents/fix-issue.sh 42

set -euo pipefail

ISSUE_NUMBER="${1:-}"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

if [ -z "$ISSUE_NUMBER" ]; then
  echo "Usage: $0 <issue-number>"
  echo "Example: $0 42"
  exit 1
fi

cd "$REPO_ROOT"

echo "🔍 Fetching issue #${ISSUE_NUMBER}..."
ISSUE_JSON=$(gh issue view "$ISSUE_NUMBER" --json title,body,labels 2>/dev/null)

if [ -z "$ISSUE_JSON" ]; then
  echo "❌ Could not fetch issue #${ISSUE_NUMBER}. Is the gh CLI authenticated?"
  exit 1
fi

ISSUE_TITLE=$(echo "$ISSUE_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])")
echo "📋 Issue: $ISSUE_TITLE"

# Create fix branch
BRANCH="fix/issue-${ISSUE_NUMBER}"
git checkout main
git pull origin main
git checkout -b "$BRANCH"

echo "🤖 Running Claude Code to fix the issue..."
claude -p "
You are fixing a bug in the Parthenon project. Read CLAUDE.md for project context.

## Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}

$(echo "$ISSUE_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('body','No description'))")

## Instructions

1. Read the relevant source files to understand the bug
2. Implement the minimum fix needed
3. Run linters: cd backend && vendor/bin/pint --test && vendor/bin/phpstan analyse
4. Run: cd frontend && npx tsc --noEmit
5. Fix any linter errors your changes introduced
6. Commit with message: fix: <description> (closes #${ISSUE_NUMBER})
7. Do NOT push or create a PR — the script will handle that
" --max-turns 20

# Check if Claude committed anything
if git log --oneline main..HEAD | grep -q .; then
  echo "📤 Pushing branch and creating PR..."
  git push origin "$BRANCH"
  gh pr create \
    --title "fix: ${ISSUE_TITLE}" \
    --body "Automated fix for #${ISSUE_NUMBER}.

---
*Generated by Claude Fix Agent (headless mode)*" \
    --base main

  echo "✅ Done! PR created for issue #${ISSUE_NUMBER}."
else
  echo "⚠️  Claude didn't commit any changes. The issue may need manual investigation."
  git checkout main
  git branch -D "$BRANCH"
  exit 1
fi
