#!/usr/bin/env bash
# nightly-maintenance.sh — Automated overnight code health sweep
#
# Usage: ./scripts/claude-agents/nightly-maintenance.sh
# Schedule: Add to crontab for nightly runs
#   0 2 * * * /home/smudoshi/Github/Parthenon/scripts/claude-agents/nightly-maintenance.sh >> /tmp/parthenon-maintenance.log 2>&1

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH="chore/nightly-maintenance-${TIMESTAMP}"

cd "$REPO_ROOT"

echo "=== Parthenon Nightly Maintenance — $(date) ==="

# Make sure we're on a clean main
git checkout main
git pull origin main

# Check if there are any issues to fix
echo "🔍 Running diagnostics..."

claude -p "
You are performing nightly maintenance on the Parthenon project. Read CLAUDE.md for context.

## Instructions

1. Run all linters and collect errors:
   - cd backend && vendor/bin/pint --test
   - cd backend && vendor/bin/phpstan analyse
   - cd frontend && npx tsc --noEmit
   - cd frontend && npx eslint .
   - cd ai && mypy app/

2. If there are ANY fixable issues (formatting, type errors, unused imports):
   - Create branch: git checkout -b ${BRANCH}
   - Fix them all
   - Run linters again to verify the fixes
   - Commit with message: chore: nightly code health fixes ($(date +%Y-%m-%d))

3. If everything is clean, just report that and do NOT create any commits.

Be conservative — only fix things that are clearly wrong. Do not refactor or change behavior.
" --max-turns 15

# Check if anything was committed
if git branch --list "$BRANCH" | grep -q .; then
  if git log --oneline main.."$BRANCH" | grep -q .; then
    echo "📤 Pushing maintenance fixes..."
    git push origin "$BRANCH"
    gh pr create \
      --title "chore: nightly code health fixes ($(date +%Y-%m-%d))" \
      --body "## Automated Maintenance

Nightly sweep found and fixed code quality issues.

Review the changes — all fixes are formatting, type hints, or lint corrections. No behavior changes.

---
*Generated by Parthenon Nightly Maintenance Agent*" \
      --base main

    echo "✅ Maintenance PR created."
  else
    echo "✅ No issues found — codebase is clean."
    git checkout main
    git branch -D "$BRANCH" 2>/dev/null || true
  fi
else
  echo "✅ No issues found — codebase is clean."
fi

echo "=== Maintenance complete — $(date) ==="
