// GENERATED — do not edit manually. Run scripts/generate-cdm-schema.py

export interface CdmColumn {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface CdmTable {
  name: string;
  domain: string;
  columns: CdmColumn[];
}

export const CDM_SCHEMA_V54: CdmTable[] = [
  {
    name: "person",
    domain: "Person",
    columns: [
      { name: "person_id", type: "integer", required: true, description: "It is assumed that every person with a different unique identifier is in fact a different person and should be treated independently." },
      { name: "gender_concept_id", type: "integer", required: true, description: "This field is meant to capture the biological sex at birth of the Person. This field should not be used to study gender identity issues." },
      { name: "year_of_birth", type: "integer", required: true, description: "Compute age using year_of_birth." },
      { name: "month_of_birth", type: "integer", required: false, description: "For data sources that provide the precise date of birth, the month should be extracted and stored in this field." },
      { name: "day_of_birth", type: "integer", required: false, description: "For data sources that provide the precise date of birth, the day should be extracted and stored in this field." },
      { name: "birth_datetime", type: "datetime", required: false, description: "This field is not required but highly encouraged. For data sources that provide the precise datetime of birth, that value should be stored in this field. If birth_datetime is not provided in the source, use the following logic to infer the date: If day_of_birth is null and month_of_birth is not n..." },
      { name: "race_concept_id", type: "integer", required: true, description: "This field captures race or ethnic background of the person." },
      { name: "ethnicity_concept_id", type: "integer", required: true, description: "This field captures Ethnicity as defined by the Office of Management and Budget (OMB) of the US Government: it distinguishes only between \"Hispanic\" and \"Not Hispanic\". Races and ethnic backgrounds are not stored here." },
      { name: "location_id", type: "integer", required: false, description: "The location refers to the physical address of the person. This field should capture the last known location of the person." },
      { name: "provider_id", type: "integer", required: false, description: "The Provider refers to the last known primary care provider (General Practitioner)." },
      { name: "care_site_id", type: "integer", required: false, description: "The Care Site refers to where the Provider typically provides the primary care." },
      { name: "person_source_value", type: "varchar", required: false, description: "Use this field to link back to persons in the source data. This is typically used for error checking of ETL logic." },
      { name: "gender_source_value", type: "varchar", required: false, description: "This field is used to store the biological sex of the person from the source data. It is not intended for use in standard analytics but for reference only." },
      { name: "gender_source_concept_id", type: "integer", required: false, description: "Due to the small number of options, this tends to be zero." },
      { name: "race_source_value", type: "varchar", required: false, description: "This field is used to store the race of the person from the source data. It is not intended for use in standard analytics but for reference only." },
      { name: "race_source_concept_id", type: "integer", required: false, description: "Due to the small number of options, this tends to be zero." },
      { name: "ethnicity_source_value", type: "varchar", required: false, description: "This field is used to store the ethnicity of the person from the source data. It is not intended for use in standard analytics but for reference only." },
      { name: "ethnicity_source_concept_id", type: "integer", required: false, description: "Due to the small number of options, this tends to be zero." },
    ],
  },
  {
    name: "observation_period",
    domain: "Observation",
    columns: [
      { name: "observation_period_id", type: "integer", required: true, description: "A Person can have multiple discrete Observation Periods which are identified by the Observation_Period_Id." },
      { name: "person_id", type: "integer", required: true, description: "The Person ID of the PERSON record for which the Observation Period is recorded." },
      { name: "observation_period_start_date", type: "date", required: true, description: "Use this date to determine the start date of the Observation Period." },
      { name: "observation_period_end_date", type: "date", required: true, description: "Use this date to determine the end date of the period for which we can assume that all events for a Person are recorded." },
      { name: "period_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Observation Period as in whether the period was determined from an insurance enrollment file, EHR healthcare encounters, or other sources." },
    ],
  },
  {
    name: "visit_occurrence",
    domain: "Visit",
    columns: [
      { name: "visit_occurrence_id", type: "integer", required: true, description: "Use this to identify unique interactions between a person and the health care system. This identifier links across the other CDM event tables to associate events with a visit." },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "visit_concept_id", type: "integer", required: true, description: "This field contains a concept id representing the kind of visit, like inpatient or outpatient. All concepts in this field should be standard and belong to the Visit domain." },
      { name: "visit_start_date", type: "date", required: true, description: "For inpatient visits, the start date is typically the admission date. For outpatient visits the start date and end date will be the same." },
      { name: "visit_start_datetime", type: "datetime", required: false, description: "If no time is given for the start date of a visit, set it to midnight (00:00:0000)." },
      { name: "visit_end_date", type: "date", required: true, description: "For inpatient visits the end date is typically the discharge date.  If a Person is still an inpatient in the hospital at the time of the data extract and does not have a visit_end_date, then set the visit_end_date to the date of the data pull." },
      { name: "visit_end_datetime", type: "datetime", required: false, description: "If a Person is still an inpatient in the hospital at the time of the data extract and does not have a visit_end_datetime, then set the visit_end_datetime to the datetime of the data pull." },
      { name: "visit_type_concept_id", type: "integer", required: true, description: "Use this field to understand the provenance of the visit record, or where the record comes from." },
      { name: "provider_id", type: "integer", required: false, description: "There will only be one provider per visit record and the ETL document should clearly state how they were chosen (attending, admitting, etc.). If there are multiple providers associated with a visit in the source, this can be reflected in the event tables (CONDITION_OCCURRENCE, PROCEDURE_OCCURRENC..." },
      { name: "care_site_id", type: "integer", required: false, description: "This field provides information about the Care Site where the Visit took place." },
      { name: "visit_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the kind of visit that took place (inpatient, outpatient, emergency, etc.)" },
      { name: "visit_source_concept_id", type: "integer", required: false, description: "If the visit source value is coded in the source data using an OMOP supported vocabulary put the concept id representing the source value here." },
      { name: "admitted_from_concept_id", type: "integer", required: false, description: "Use this field to determine where the patient was admitted from. This concept is part of the visit domain and can indicate if a patient was admitted to the hospital from a long-term care facility, for example." },
      { name: "admitted_from_source_value", type: "varchar", required: false, description: "This information may be called something different in the source data but the field is meant to contain a value indicating where a person was admitted from. Typically this applies only to visits that have a length of stay, like inpatient visits or long-term care visits." },
      { name: "discharged_to_concept_id", type: "integer", required: false, description: "Use this field to determine where the patient was discharged to after a visit. This concept is part of the visit domain and can indicate if a patient was transferred to another hospital or sent to a long-term care facility, for example.  It is assumed that a person is discharged to home therefore..." },
      { name: "discharged_to_source_value", type: "varchar", required: false, description: "This information may be called something different in the source data but the field is meant to contain a value indicating where a person was discharged to after a visit, as in they went home or were moved to long-term care. Typically this applies only to visits that have a length of stay of a da..." },
      { name: "preceding_visit_occurrence_id", type: "integer", required: false, description: "Use this field to find the visit that occurred for the person prior to the given visit. There could be a few days or a few years in between." },
    ],
  },
  {
    name: "visit_detail",
    domain: "Visit",
    columns: [
      { name: "visit_detail_id", type: "integer", required: true, description: "Use this to identify unique interactions between a person and the health care system. This identifier links across the other CDM event tables to associate events with a visit detail." },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "visit_detail_concept_id", type: "integer", required: true, description: "This field contains a concept id representing the kind of visit detail, like inpatient or outpatient. All concepts in this field should be standard and belong to the Visit domain." },
      { name: "visit_detail_start_date", type: "date", required: true, description: "This is the date of the start of the encounter. This may or may not be equal to the date of the Visit the Visit Detail is associated with." },
      { name: "visit_detail_start_datetime", type: "datetime", required: false, description: "If no time is given for the start date of a visit, set it to midnight (00:00:0000)." },
      { name: "visit_detail_end_date", type: "date", required: true, description: "This the end date of the patient-provider interaction.  If a Person is still an inpatient in the hospital at the time of the data extract and does not have a visit_end_date, then set the visit_end_date to the date of the data pull." },
      { name: "visit_detail_end_datetime", type: "datetime", required: false, description: "If a Person is still an inpatient in the hospital at the time of the data extract and does not have a visit_end_datetime, then set the visit_end_datetime to the datetime of the data pull." },
      { name: "visit_detail_type_concept_id", type: "integer", required: true, description: "Use this field to understand the provenance of the visit detail record, or where the record comes from." },
      { name: "provider_id", type: "integer", required: false, description: "There will only be one provider per  **visit** record and the ETL document should clearly state how they were chosen (attending, admitting, etc.). This is a typical reason for leveraging the VISIT_DETAIL table as even though each VISIT_DETAIL record can only have one provider, there is no limit t..." },
      { name: "care_site_id", type: "integer", required: false, description: "This field provides information about the Care Site where the Visit Detail took place." },
      { name: "visit_detail_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the kind of visit detail that took place (inpatient, outpatient, emergency, etc.)" },
      { name: "visit_detail_source_concept_id", type: "integer", required: false, description: "If the VISIT_DETAIL_SOURCE_VALUE is coded in the source data using an OMOP supported vocabulary put the concept id representing the source value here." },
      { name: "admitted_from_concept_id", type: "integer", required: false, description: "Use this field to determine where the patient was admitted from. This concept is part of the visit domain and can indicate if a patient was admitted to the hospital from a long-term care facility, for example." },
      { name: "admitted_from_source_value", type: "varchar", required: false, description: "This information may be called something different in the source data but the field is meant to contain a value indicating where a person was admitted from. Typically this applies only to visits that have a length of stay, like inpatient visits or long-term care visits." },
      { name: "discharged_to_source_value", type: "varchar", required: false, description: "This information may be called something different in the source data but the field is meant to contain a value indicating where a person was discharged to after a visit, as in they went home or were moved to long-term care. Typically this applies only to visits that have a length of stay of a da..." },
      { name: "discharged_to_concept_id", type: "integer", required: false, description: "Use this field to determine where the patient was discharged to after a visit. This concept is part of the visit domain and can indicate if a patient was transferred to another hospital or sent to a long-term care facility, for example.  It is assumed that a person is discharged to home therefore..." },
      { name: "preceding_visit_detail_id", type: "integer", required: false, description: "Use this field to find the visit detail that occurred for the person prior to the given visit detail record. There could be a few days or a few years in between." },
      { name: "parent_visit_detail_id", type: "integer", required: false, description: "Use this field to find the visit detail that subsumes the given visit detail record. This is used in the case that a visit detail record needs to be nested beyond the VISIT_OCCURRENCE/VISIT_DETAIL relationship." },
      { name: "visit_occurrence_id", type: "integer", required: true, description: "Use this field to link the VISIT_DETAIL record to its VISIT_OCCURRENCE." },
    ],
  },
  {
    name: "condition_occurrence",
    domain: "Condition",
    columns: [
      { name: "condition_occurrence_id", type: "integer", required: true, description: "The unique key given to a condition record for a person. Refer to the ETL for how duplicate conditions during the same visit were handled." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the PERSON for whom the condition is recorded." },
      { name: "condition_concept_id", type: "integer", required: true, description: "The CONDITION_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies. This is the standard concept mapped from the source value which represents a condition" },
      { name: "condition_start_date", type: "date", required: true, description: "Use this date to determine the start date of the condition" },
      { name: "condition_start_datetime", type: "datetime", required: false, description: "If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "condition_end_date", type: "date", required: false, description: "Use this date to determine the end date of the condition" },
      { name: "condition_end_datetime", type: "datetime", required: false, description: "If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "condition_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Condition record, as in whether the condition was from an EHR system, insurance claim, registry, or other sources." },
      { name: "condition_status_concept_id", type: "integer", required: false, description: "This concept represents the point during the visit the diagnosis was given (admitting diagnosis, final diagnosis), whether the diagnosis was determined due to laboratory findings, if the diagnosis was exclusionary, or if it was a preliminary diagnosis, among others." },
      { name: "stop_reason", type: "varchar", required: false, description: "The Stop Reason indicates why a Condition is no longer valid with respect to the purpose within the source data. Note that a Stop Reason does not necessarily imply that the condition is no longer occurring." },
      { name: "provider_id", type: "integer", required: false, description: "The provider associated with condition record, e.g. the provider who made the diagnosis or the provider who recorded the symptom." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The visit during which the condition occurred." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The VISIT_DETAIL record during which the condition occurred. For example, if the person was in the ICU at the time of the diagnosis the VISIT_OCCURRENCE record would reflect the overall hospital stay and the VISIT_DETAIL record would reflect the ICU stay during the hospital visit." },
      { name: "condition_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the condition that occurred. For example, this could be an ICD10 or Read code." },
      { name: "condition_source_concept_id", type: "integer", required: false, description: "This is the concept representing the condition source value and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not a..." },
      { name: "condition_status_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the condition status." },
    ],
  },
  {
    name: "drug_exposure",
    domain: "Drug",
    columns: [
      { name: "drug_exposure_id", type: "integer", required: true, description: "The unique key given to records of drug dispensings or administrations for a person. Refer to the ETL for how duplicate drugs during the same visit were handled." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the PERSON for whom the drug dispensing or administration is recorded. This may be a system generated code." },
      { name: "drug_concept_id", type: "integer", required: true, description: "The DRUG_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies. This is the standard concept mapped from the source concept id which represents a drug product or molecule otherwise introduced to the body. The drug concepts can have a varying degree of i..." },
      { name: "drug_exposure_start_date", type: "date", required: true, description: "Use this date to determine the start date of the drug record." },
      { name: "drug_exposure_start_datetime", type: "datetime", required: false, description: "This is not required, though it is in v6. If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "drug_exposure_end_date", type: "date", required: true, description: "The DRUG_EXPOSURE_END_DATE denotes the day the drug exposure ended for the patient." },
      { name: "drug_exposure_end_datetime", type: "datetime", required: false, description: "This is not required, though it is in v6. If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "verbatim_end_date", type: "date", required: false, description: "This is the end date of the drug exposure as it appears in the source data, if it is given" },
      { name: "drug_type_concept_id", type: "integer", required: true, description: "You can use the TYPE_CONCEPT_ID to delineate between prescriptions written vs. prescriptions dispensed vs. medication history vs. patient-reported exposure, etc." },
      { name: "stop_reason", type: "varchar", required: false, description: "The reason a person stopped a medication as it is represented in the source. Reasons include regimen completed, changed, removed, etc. This field will be retired in v6.0." },
      { name: "refills", type: "integer", required: false, description: "This is only filled in when the record is coming from a prescription written this field is meant to represent intended refills at time of the prescription." },
      { name: "quantity", type: "float", required: false, description: "To find the dose form of a drug the RELATIONSHIP table can be used where the relationship_id is 'Has dose form'. If liquid, quantity stands for the total amount dispensed or ordered of ingredient in the units given by the drug_strength table. If the unit from the source data does not align with t..." },
      { name: "days_supply", type: "integer", required: false, description: "Days supply of the drug. This should be the verbatim days_supply as given on the prescription. If the drug is physician administered use duration end date if given or set to 1 as default if duration is not available." },
      { name: "sig", type: "varchar", required: false, description: "This is the verbatim instruction for the drug as written by the provider." },
      { name: "route_concept_id", type: "integer", required: false, description: "The standard CONCEPT_ID that the ROUTE_SOURCE_VALUE maps to in the route domain." },
      { name: "lot_number", type: "varchar", required: false, description: "" },
      { name: "provider_id", type: "integer", required: false, description: "The Provider associated with drug record, e.g. the provider who wrote the prescription or the provider who administered the drug." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The Visit during which the drug was prescribed, administered or dispensed." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The VISIT_DETAIL record during which the drug exposure occurred. For example, if the person was in the ICU at the time of the drug administration the VISIT_OCCURRENCE record would reflect the overall hospital stay and the VISIT_DETAIL record would reflect the ICU stay during the hospital visit." },
      { name: "drug_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the drug exposure that occurred. For example, this could be an NDC or Gemscript code." },
      { name: "drug_source_concept_id", type: "integer", required: false, description: "This is the concept representing the drug source value and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not adequa..." },
      { name: "route_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the drug route." },
      { name: "dose_unit_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the dose unit of the drug given." },
    ],
  },
  {
    name: "procedure_occurrence",
    domain: "Procedure",
    columns: [
      { name: "procedure_occurrence_id", type: "integer", required: true, description: "The unique key given to a procedure record for a person. Refer to the ETL for how duplicate procedures during the same visit were handled." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the PERSON for whom the procedure is recorded. This may be a system generated code." },
      { name: "procedure_concept_id", type: "integer", required: true, description: "The PROCEDURE_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies. This is the standard concept mapped from the source value which represents a procedure" },
      { name: "procedure_date", type: "date", required: true, description: "Use this date to determine the date the procedure started." },
      { name: "procedure_datetime", type: "datetime", required: false, description: "If the procedure has a start time in the native date, use this field to house that information. This will be renamed in a future version to **PROCEDURE_START_DATETIME**." },
      { name: "procedure_end_date", type: "date", required: false, description: "Use this field to house the date that the procedure ended." },
      { name: "procedure_end_datetime", type: "datetime", required: false, description: "Use this field to house the datetime that the procedure ended." },
      { name: "procedure_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Procedure record, as in whether the procedure was from an EHR system, insurance claim, registry, or other sources." },
      { name: "modifier_concept_id", type: "integer", required: false, description: "The modifiers are intended to give additional information about the procedure but as of now the vocabulary is under review." },
      { name: "quantity", type: "integer", required: false, description: "If the quantity value is omitted, a single procedure is assumed." },
      { name: "provider_id", type: "integer", required: false, description: "The provider associated with the procedure record, e.g. the provider who performed the Procedure." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The visit during which the procedure occurred." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The VISIT_DETAIL record during which the Procedure occurred. For example, if the Person was in the ICU at the time of the Procedure the VISIT_OCCURRENCE record would reflect the overall hospital stay and the VISIT_DETAIL record would reflect the ICU stay during the hospital visit." },
      { name: "procedure_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the procedure that occurred. For example, this could be an CPT4 or OPCS4 code." },
      { name: "procedure_source_concept_id", type: "integer", required: false, description: "This is the concept representing the procedure source value and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not a..." },
      { name: "modifier_source_value", type: "varchar", required: false, description: "The original modifier code from the source is stored here for reference." },
    ],
  },
  {
    name: "device_exposure",
    domain: "Device",
    columns: [
      { name: "device_exposure_id", type: "integer", required: true, description: "The unique key given to records a person's exposure to a foreign physical object or instrument." },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "device_concept_id", type: "integer", required: true, description: "The DEVICE_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies. This is the standard concept mapped from the source concept id which represents a foreign object or instrument the person was exposed to." },
      { name: "device_exposure_start_date", type: "date", required: true, description: "Use this date to determine the start date of the device record." },
      { name: "device_exposure_start_datetime", type: "datetime", required: false, description: "This is not required, though it is in v6. If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "device_exposure_end_date", type: "date", required: false, description: "The DEVICE_EXPOSURE_END_DATE denotes the day the device exposure ended for the patient, if given." },
      { name: "device_exposure_end_datetime", type: "datetime", required: false, description: "If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "device_type_concept_id", type: "integer", required: true, description: "You can use the TYPE_CONCEPT_ID to denote the provenance of the record, as in whether the record is from administrative claims or EHR." },
      { name: "unique_device_id", type: "varchar", required: false, description: "This is the Unique Device Identification (UDI-DI) number for devices regulated by the FDA, if given." },
      { name: "production_id", type: "varchar", required: false, description: "This is the Production Identifier (UDI-PI) portion of the Unique Device Identification." },
      { name: "quantity", type: "integer", required: false, description: "" },
      { name: "provider_id", type: "integer", required: false, description: "The Provider associated with device record, e.g. the provider who wrote the prescription or the provider who implanted the device." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The Visit during which the device was prescribed or given." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The Visit Detail during which the device was prescribed or given." },
      { name: "device_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the device exposure that occurred. For example, this could be an NDC or Gemscript code." },
      { name: "device_source_concept_id", type: "integer", required: false, description: "This is the concept representing the device source value and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not adeq..." },
      { name: "unit_concept_id", type: "integer", required: false, description: "UNIT_SOURCE_VALUES should be mapped to a Standard Concept in the Unit domain that best represents the unit as given in the source data." },
      { name: "unit_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the unit of the Device. For example, blood transfusions are considered devices and can be given in mL quantities." },
      { name: "unit_source_concept_id", type: "integer", required: false, description: "This is the concept representing the UNIT_SOURCE_VALUE and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not adequa..." },
    ],
  },
  {
    name: "measurement",
    domain: "Measurement",
    columns: [
      { name: "measurement_id", type: "integer", required: true, description: "The unique key given to a Measurement record for a Person. Refer to the ETL for how duplicate Measurements during the same Visit were handled." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the Person for whom the Measurement is recorded. This may be a system generated code." },
      { name: "measurement_concept_id", type: "integer", required: true, description: "The MEASUREMENT_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies." },
      { name: "measurement_date", type: "date", required: true, description: "Use this date to determine the date of the measurement." },
      { name: "measurement_datetime", type: "datetime", required: false, description: "This is not required, though it is in v6. If a source does not specify datetime the convention is to set the time to midnight (00:00:0000)" },
      { name: "measurement_time", type: "varchar", required: false, description: "This is present for backwards compatibility and will be deprecated in an upcoming version." },
      { name: "measurement_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Measurement record, as in whether the measurement was from an EHR system, insurance claim, registry, or other sources." },
      { name: "operator_concept_id", type: "integer", required: false, description: "The meaning of Concept [4172703](https://athena.ohdsi.org/search-terms/terms/4172703) for '=' is identical to omission of a OPERATOR_CONCEPT_ID value. Since the use of this field is rare, it's important when devising analyses to not to forget testing for the content of this field for values diffe..." },
      { name: "value_as_number", type: "float", required: false, description: "This is the numerical value of the Result of the Measurement, if available. Note that measurements such as blood pressures will be split into their component parts i.e. one record for systolic, one record for diastolic." },
      { name: "value_as_concept_id", type: "integer", required: false, description: "If the raw data gives a categorial result for measurements those values are captured and mapped to standard concepts in the 'Meas Value' domain." },
      { name: "unit_concept_id", type: "integer", required: false, description: "There is currently no recommended unit for individual measurements, i.e. it is not mandatory to represent Hemoglobin a1C measurements as a percentage. UNIT_SOURCE_VALUES should be mapped to a Standard Concept in the Unit domain that best represents the unit as given in the source data." },
      { name: "range_low", type: "float", required: false, description: "Ranges have the same unit as the VALUE_AS_NUMBER. These ranges are provided by the source and should remain NULL if not given." },
      { name: "range_high", type: "float", required: false, description: "Ranges have the same unit as the VALUE_AS_NUMBER. These ranges are provided by the source and should remain NULL if not given." },
      { name: "provider_id", type: "integer", required: false, description: "The provider associated with measurement record, e.g. the provider who ordered the test or the provider who recorded the result." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The visit during which the Measurement occurred." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The VISIT_DETAIL record during which the Measurement occurred. For example, if the Person was in the ICU at the time the VISIT_OCCURRENCE record would reflect the overall hospital stay and the VISIT_DETAIL record would reflect the ICU stay during the hospital visit." },
      { name: "measurement_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the Measurement that occurred. For example, this could be an ICD10 or Read code." },
      { name: "measurement_source_concept_id", type: "integer", required: false, description: "This is the concept representing the MEASUREMENT_SOURCE_VALUE and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not..." },
      { name: "unit_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the unit of the Measurement that occurred." },
      { name: "unit_source_concept_id", type: "integer", required: false, description: "\"This is the concept representing the UNIT_SOURCE_VALUE and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not adequ..." },
      { name: "value_source_value", type: "varchar", required: false, description: "This field houses the verbatim result value of the Measurement from the source data ." },
      { name: "measurement_event_id", type: "integer", required: false, description: "If the Measurement record is related to another record in the database, this field is the primary key of the linked record." },
      { name: "meas_event_field_concept_id", type: "integer", required: false, description: "If the Measurement record is related to another record in the database, this field is the CONCEPT_ID that identifies which table the primary key of the linked record came from." },
    ],
  },
  {
    name: "observation",
    domain: "Observation",
    columns: [
      { name: "observation_id", type: "integer", required: true, description: "The unique key given to an Observation record for a Person. Refer to the ETL for how duplicate Observations during the same Visit were handled." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the Person for whom the Observation is recorded. This may be a system generated code." },
      { name: "observation_concept_id", type: "integer", required: true, description: "The OBSERVATION_CONCEPT_ID field is recommended for primary use in analyses, and must be used for network studies." },
      { name: "observation_date", type: "date", required: true, description: "The date of the Observation. Depending on what the Observation represents this could be the date of a lab test, the date of a survey, or the date a patient's family history was taken." },
      { name: "observation_datetime", type: "datetime", required: false, description: "If no time is given set to midnight (00:00:00)." },
      { name: "observation_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Observation record, as in whether the measurement was from an EHR system, insurance claim, registry, or other sources." },
      { name: "value_as_number", type: "float", required: false, description: "This is the numerical value of the Result of the Observation, if applicable and available. It is not expected that all Observations will have numeric results, rather, this field is here to house values should they exist." },
      { name: "value_as_string", type: "varchar", required: false, description: "This is the categorical value of the Result of the Observation, if applicable and available." },
      { name: "value_as_concept_id", type: "integer", required: false, description: "It is possible that some records destined for the Observation table have two clinical ideas represented in one source code. This is common with ICD10 codes that describe a family history of some Condition, for example. In OMOP the Vocabulary breaks these two clinical ideas into two codes; one bec..." },
      { name: "qualifier_concept_id", type: "integer", required: false, description: "This field contains all attributes specifying the clinical fact further, such as as degrees, severities, drug-drug interaction alerts etc." },
      { name: "unit_concept_id", type: "integer", required: false, description: "There is currently no recommended unit for individual observation concepts. UNIT_SOURCE_VALUES should be mapped to a Standard Concept in the Unit domain that best represents the unit as given in the source data." },
      { name: "provider_id", type: "integer", required: false, description: "The provider associated with the observation record, e.g. the provider who ordered the test or the provider who recorded the result." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The visit during which the Observation occurred." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The VISIT_DETAIL record during which the Observation occurred. For example, if the Person was in the ICU at the time the VISIT_OCCURRENCE record would reflect the overall hospital stay and the VISIT_DETAIL record would reflect the ICU stay during the hospital visit." },
      { name: "observation_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the Observation that occurred. For example, this could be an ICD10 or Read code." },
      { name: "observation_source_concept_id", type: "integer", required: false, description: "This is the concept representing the OBSERVATION_SOURCE_VALUE and may not necessarily be standard. This field is discouraged from use in analysis because it is not required to contain Standard Concepts that are used across the OHDSI community, and should only be used when Standard Concepts do not..." },
      { name: "unit_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the unit of the Observation that occurred." },
      { name: "qualifier_source_value", type: "varchar", required: false, description: "This field houses the verbatim value from the source data representing the qualifier of the Observation that occurred." },
      { name: "value_source_value", type: "varchar", required: false, description: "This field houses the verbatim result value of the Observation from the source data.  Do not get confused with the Observation_source_value which captures source value of the observation mapped to observation_concept_id. This field is the observation result value from the source." },
      { name: "observation_event_id", type: "integer", required: false, description: "If the Observation record is related to another record in the database, this field is the primary key of the linked record." },
      { name: "obs_event_field_concept_id", type: "integer", required: false, description: "If the Observation record is related to another record in the database, this field is the CONCEPT_ID that identifies which table the primary key of the linked record came from." },
    ],
  },
  {
    name: "death",
    domain: "Death",
    columns: [
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "death_date", type: "date", required: true, description: "The date the person was deceased." },
      { name: "death_datetime", type: "datetime", required: false, description: "If not available set time to midnight (00:00:00)" },
      { name: "death_type_concept_id", type: "integer", required: false, description: "This is the provenance of the death record, i.e., where it came from. It is possible that an administrative claims database would source death information from a government file so do not assume the Death Type is the same as the Visit Type, etc." },
      { name: "cause_concept_id", type: "integer", required: false, description: "This is the Standard Concept representing the Person's cause of death, if available." },
      { name: "cause_source_value", type: "varchar", required: false, description: "If available, put the source code representing the cause of death here." },
      { name: "cause_source_concept_id", type: "integer", required: false, description: "If the cause of death was coded using a Vocabulary present in the OMOP Vocabularies put the CONCEPT_ID representing the cause of death here." },
    ],
  },
  {
    name: "note",
    domain: "Note",
    columns: [
      { name: "note_id", type: "integer", required: true, description: "A unique identifier for each note." },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "note_date", type: "date", required: true, description: "The date the note was recorded." },
      { name: "note_datetime", type: "datetime", required: false, description: "If time is not given set the time to midnight." },
      { name: "note_type_concept_id", type: "integer", required: true, description: "The provenance of the note. Most likely this will be EHR." },
      { name: "note_class_concept_id", type: "integer", required: true, description: "A Standard Concept Id representing the HL7 LOINC Document Type Vocabulary classification of the note." },
      { name: "note_title", type: "varchar", required: false, description: "The title of the note." },
      { name: "note_text", type: "varchar", required: true, description: "The content of the note." },
      { name: "encoding_concept_id", type: "integer", required: true, description: "This is the Concept representing the character encoding type." },
      { name: "language_concept_id", type: "integer", required: true, description: "The language of the note." },
      { name: "provider_id", type: "integer", required: false, description: "The Provider who wrote the note." },
      { name: "visit_occurrence_id", type: "integer", required: false, description: "The Visit during which the note was written." },
      { name: "visit_detail_id", type: "integer", required: false, description: "The Visit Detail during which the note was written." },
      { name: "note_source_value", type: "varchar", required: false, description: "The source value mapped to the NOTE_CLASS_CONCEPT_ID." },
      { name: "note_event_id", type: "integer", required: false, description: "If the Note record is related to another record in the database, this field is the primary key of the linked record." },
      { name: "note_event_field_concept_id", type: "integer", required: false, description: "If the Note record is related to another record in the database, this field is the CONCEPT_ID that identifies which table the primary key of the linked record came from." },
    ],
  },
  {
    name: "note_nlp",
    domain: "Note",
    columns: [
      { name: "note_nlp_id", type: "integer", required: true, description: "A unique identifier for the NLP record." },
      { name: "note_id", type: "integer", required: true, description: "This is the NOTE_ID for the NOTE record the NLP record is associated to." },
      { name: "section_concept_id", type: "integer", required: false, description: "The SECTION_CONCEPT_ID should be used to represent the note section contained in the NOTE_NLP record. These concepts can be found as parts of document panels and are based on the type of note written, i.e. a discharge summary. These panels can be found as concepts with the relationship 'Subsumes'..." },
      { name: "snippet", type: "varchar", required: false, description: "A small window of text surrounding the term" },
      { name: "offset", type: "varchar", required: false, description: "Character offset of the extracted term in the input note" },
      { name: "lexical_variant", type: "varchar", required: true, description: "Raw text extracted from the NLP tool." },
      { name: "note_nlp_concept_id", type: "integer", required: false, description: "" },
      { name: "note_nlp_source_concept_id", type: "integer", required: false, description: "" },
      { name: "nlp_system", type: "varchar", required: false, description: "Name and version of the NLP system that extracted the term. Useful for data provenance." },
      { name: "nlp_date", type: "date", required: true, description: "The date of the note processing." },
      { name: "nlp_datetime", type: "datetime", required: false, description: "The date and time of the note processing." },
      { name: "term_exists", type: "varchar", required: false, description: "Term_exists is defined as a flag that indicates if the patient actually has or had the condition. Any of the following modifiers would make Term_exists false: Negation = true Subject = [anything other than the patient] Conditional = true/li> Rule_out = true Uncertain = very low certainty or any l..." },
      { name: "term_temporal", type: "varchar", required: false, description: "Term_temporal is to indicate if a condition is present or just in the past. The following would be past:<br><br> - History = true - Concept_date = anything before the time of the report" },
      { name: "term_modifiers", type: "varchar", required: false, description: "For the modifiers that are there, they would have to have these values:<br><br> - Negation = false - Subject = patient - Conditional = false - Rule_out = false - Uncertain = true or high or moderate or even low (could argue about low). Term_modifiers will concatenate all modifiers for different t..." },
    ],
  },
  {
    name: "specimen",
    domain: "Specimen",
    columns: [
      { name: "specimen_id", type: "integer", required: true, description: "Unique identifier for each specimen." },
      { name: "person_id", type: "integer", required: true, description: "The person from whom the specimen is collected." },
      { name: "specimen_concept_id", type: "integer", required: true, description: "The standard CONCEPT_ID that the SPECIMEN_SOURCE_VALUE maps to in the specimen domain. [Accepted Concepts](https://athena.ohdsi.org/search-terms/terms?domain=Specimen&standardConcept=Standard&page=1&pageSize=15&query=)" },
      { name: "specimen_type_concept_id", type: "integer", required: true, description: "Put the source of the specimen record, as in an EHR system. [Accepted Concepts](https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Type+Concept&page=1&pageSize=15&query=)." },
      { name: "specimen_date", type: "date", required: true, description: "The date the specimen was collected." },
      { name: "specimen_datetime", type: "datetime", required: false, description: "" },
      { name: "quantity", type: "float", required: false, description: "The amount of specimen collected from the person." },
      { name: "unit_concept_id", type: "integer", required: false, description: "The unit for the quantity of the specimen." },
      { name: "anatomic_site_concept_id", type: "integer", required: false, description: "This is the site on the body where the specimen is from." },
      { name: "disease_status_concept_id", type: "integer", required: false, description: "" },
      { name: "specimen_source_id", type: "varchar", required: false, description: "This is the identifier for the specimen from the source system." },
      { name: "specimen_source_value", type: "varchar", required: false, description: "" },
      { name: "unit_source_value", type: "varchar", required: false, description: "This unit for the quantity of the specimen, as represented in the source." },
      { name: "anatomic_site_source_value", type: "varchar", required: false, description: "This is the site on the body where the specimen was taken from, as represented in the source." },
      { name: "disease_status_source_value", type: "varchar", required: false, description: "" },
    ],
  },
  {
    name: "fact_relationship",
    domain: "Other",
    columns: [
      { name: "domain_concept_id_1", type: "integer", required: true, description: "" },
      { name: "fact_id_1", type: "integer", required: true, description: "" },
      { name: "domain_concept_id_2", type: "integer", required: true, description: "" },
      { name: "fact_id_2", type: "integer", required: true, description: "" },
      { name: "relationship_concept_id", type: "integer", required: true, description: "" },
    ],
  },
  {
    name: "location",
    domain: "Location",
    columns: [
      { name: "location_id", type: "integer", required: true, description: "The unique key given to a unique Location." },
      { name: "address_1", type: "varchar", required: false, description: "This is the first line of the address." },
      { name: "address_2", type: "varchar", required: false, description: "This is the second line of the address" },
      { name: "city", type: "varchar", required: false, description: "" },
      { name: "state", type: "varchar", required: false, description: "" },
      { name: "zip", type: "varchar", required: false, description: "Zip codes are handled as strings of up to 9 characters length. For US addresses, these represent either a 3-digit abbreviated Zip code as provided by many sources for patient protection reasons, the full 5-digit Zip or the 9-digit (ZIP + 4) codes. Unless for specific reasons analytical methods sh..." },
      { name: "county", type: "varchar", required: false, description: "" },
      { name: "location_source_value", type: "varchar", required: false, description: "Put the verbatim value for the location here, as it shows up in the source." },
      { name: "country_concept_id", type: "integer", required: false, description: "The Concept Id representing the country. Values should conform to the [Geography](https://athena.ohdsi.org/search-terms/terms?domain=Geography&standardConcept=Standard&page=1&pageSize=15&query=&boosts) domain." },
      { name: "country_source_value", type: "varchar", required: false, description: "The name of the country." },
      { name: "latitude", type: "float", required: false, description: "Must be between -90 and 90." },
      { name: "longitude", type: "float", required: false, description: "Must be between -180 and 180." },
    ],
  },
  {
    name: "care_site",
    domain: "Location",
    columns: [
      { name: "care_site_id", type: "integer", required: true, description: "Assign an id to each unique combination of location_id and place_of_service_source_value" },
      { name: "care_site_name", type: "varchar", required: false, description: "The name of the care_site as it appears in the source data" },
      { name: "place_of_service_concept_id", type: "integer", required: false, description: "This is a high-level way of characterizing a Care Site. Typically, however, Care Sites can provide care in multiple settings (inpatient, outpatient, etc.) and this granularity should be reflected in the visit." },
      { name: "location_id", type: "integer", required: false, description: "The location_id from the LOCATION table representing the physical location of the care_site." },
      { name: "care_site_source_value", type: "varchar", required: false, description: "The identifier of the care_site as it appears in the source data. This could be an identifier separate from the name of the care_site." },
      { name: "place_of_service_source_value", type: "varchar", required: false, description: "Put the place of service of the care_site as it appears in the source data." },
    ],
  },
  {
    name: "provider",
    domain: "Location",
    columns: [
      { name: "provider_id", type: "integer", required: true, description: "It is assumed that every provider with a different unique identifier is in fact a different person and should be treated independently." },
      { name: "provider_name", type: "varchar", required: false, description: "This field is not necessary as it is not necessary to have the actual identity of the Provider. Rather, the idea is to uniquely and anonymously identify providers of care across the database." },
      { name: "npi", type: "varchar", required: false, description: "This is the National Provider Number issued to health care providers in the US by the Centers for Medicare and Medicaid Services (CMS)." },
      { name: "dea", type: "varchar", required: false, description: "This is the identifier issued by the DEA, a US federal agency, that allows a provider to write prescriptions for controlled substances." },
      { name: "specialty_concept_id", type: "integer", required: false, description: "This field either represents the most common specialty that occurs in the data or the most specific concept that represents all specialties listed, should the provider have more than one. This includes physician specialties such as internal medicine, emergency medicine, etc. and allied health pro..." },
      { name: "care_site_id", type: "integer", required: false, description: "This is the CARE_SITE_ID for the location that the provider primarily practices in." },
      { name: "year_of_birth", type: "integer", required: false, description: "" },
      { name: "gender_concept_id", type: "integer", required: false, description: "This field represents the recorded gender of the provider in the source data." },
      { name: "provider_source_value", type: "varchar", required: false, description: "Use this field to link back to providers in the source data. This is typically used for error checking of ETL logic." },
      { name: "specialty_source_value", type: "varchar", required: false, description: "This is the kind of provider or specialty as it appears in the source data. This includes physician specialties such as internal medicine, emergency medicine, etc. and allied health professionals such as nurses, midwives, and pharmacists." },
      { name: "specialty_source_concept_id", type: "integer", required: false, description: "This is often zero as many sites use proprietary codes to store physician speciality." },
      { name: "gender_source_value", type: "varchar", required: false, description: "This is provider's gender as it appears in the source data." },
      { name: "gender_source_concept_id", type: "integer", required: false, description: "This is often zero as many sites use proprietary codes to store provider gender." },
    ],
  },
  {
    name: "payer_plan_period",
    domain: "Cost",
    columns: [
      { name: "payer_plan_period_id", type: "integer", required: true, description: "A unique identifier for each unique combination of a Person, Payer, Plan, and Period of time." },
      { name: "person_id", type: "integer", required: true, description: "The Person covered by the Plan." },
      { name: "payer_plan_period_start_date", type: "date", required: true, description: "Start date of Plan coverage." },
      { name: "payer_plan_period_end_date", type: "date", required: true, description: "End date of Plan coverage." },
      { name: "payer_concept_id", type: "integer", required: false, description: "This field represents the organization who reimburses the provider which administers care to the Person." },
      { name: "payer_source_value", type: "varchar", required: false, description: "This is the Payer as it appears in the source data." },
      { name: "payer_source_concept_id", type: "integer", required: false, description: "If the source data codes the Payer in an OMOP supported vocabulary store the concept_id here." },
      { name: "plan_concept_id", type: "integer", required: false, description: "This field represents the specific health benefit Plan the Person is enrolled in." },
      { name: "plan_source_value", type: "varchar", required: false, description: "This is the health benefit Plan of the Person as it appears in the source data." },
      { name: "plan_source_concept_id", type: "integer", required: false, description: "If the source data codes the Plan in an OMOP supported vocabulary store the concept_id here." },
      { name: "sponsor_concept_id", type: "integer", required: false, description: "This field represents the sponsor of the Plan who finances the Plan. This includes self-insured, small group health plan and large group health plan." },
      { name: "sponsor_source_value", type: "varchar", required: false, description: "The Plan sponsor as it appears in the source data." },
      { name: "sponsor_source_concept_id", type: "integer", required: false, description: "If the source data codes the sponsor in an OMOP supported vocabulary store the concept_id here." },
      { name: "family_source_value", type: "varchar", required: false, description: "The common identifier for all people (often a family) that covered by the same policy." },
      { name: "stop_reason_concept_id", type: "integer", required: false, description: "This field represents the reason the Person left the Plan, if known." },
      { name: "stop_reason_source_value", type: "varchar", required: false, description: "The Plan stop reason as it appears in the source data." },
      { name: "stop_reason_source_concept_id", type: "integer", required: false, description: "If the source data codes the stop reason in an OMOP supported vocabulary store the concept_id here." },
    ],
  },
  {
    name: "cost",
    domain: "Cost",
    columns: [
      { name: "cost_id", type: "integer", required: true, description: "" },
      { name: "cost_event_id", type: "integer", required: true, description: "" },
      { name: "cost_domain_id", type: "varchar", required: true, description: "" },
      { name: "cost_type_concept_id", type: "integer", required: true, description: "" },
      { name: "currency_concept_id", type: "integer", required: false, description: "" },
      { name: "total_charge", type: "float", required: false, description: "" },
      { name: "total_cost", type: "float", required: false, description: "" },
      { name: "total_paid", type: "float", required: false, description: "" },
      { name: "paid_by_payer", type: "float", required: false, description: "" },
      { name: "paid_by_patient", type: "float", required: false, description: "" },
      { name: "paid_patient_copay", type: "float", required: false, description: "" },
      { name: "paid_patient_coinsurance", type: "float", required: false, description: "" },
      { name: "paid_patient_deductible", type: "float", required: false, description: "" },
      { name: "paid_by_primary", type: "float", required: false, description: "" },
      { name: "paid_ingredient_cost", type: "float", required: false, description: "" },
      { name: "paid_dispensing_fee", type: "float", required: false, description: "" },
      { name: "payer_plan_period_id", type: "integer", required: false, description: "" },
      { name: "amount_allowed", type: "float", required: false, description: "" },
      { name: "revenue_code_concept_id", type: "integer", required: false, description: "" },
      { name: "revenue_code_source_value", type: "varchar", required: false, description: "Revenue codes are a method to charge for a class of procedures and conditions in the U.S. hospital system." },
      { name: "drg_concept_id", type: "integer", required: false, description: "" },
      { name: "drg_source_value", type: "varchar", required: false, description: "Diagnosis Related Groups are US codes used to classify hospital cases into one of approximately 500 groups." },
    ],
  },
  {
    name: "drug_era",
    domain: "Drug",
    columns: [
      { name: "drug_era_id", type: "integer", required: true, description: "" },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "drug_concept_id", type: "integer", required: true, description: "The Concept Id representing the specific drug ingredient." },
      { name: "drug_era_start_date", type: "datetime", required: true, description: "The Drug Era Start Date is the start date of the first Drug Exposure for a given ingredient, with at least 31 days since the previous exposure." },
      { name: "drug_era_end_date", type: "datetime", required: true, description: "The Drug Era End Date is the end date of the last Drug Exposure. The End Date of each Drug Exposure is either taken from the field drug_exposure_end_date or, as it is typically not available, inferred using the following rules: For pharmacy prescription data, the date when the drug was dispensed ..." },
      { name: "drug_exposure_count", type: "integer", required: false, description: "" },
      { name: "gap_days", type: "integer", required: false, description: "The Gap Days determine how many total drug-free days are observed between all Drug Exposure events that contribute to a DRUG_ERA record. It is assumed that the drugs are \"not stockpiled\" by the patient, i.e. that if a new drug prescription or refill is observed (a new DRUG_EXPOSURE record is writ..." },
    ],
  },
  {
    name: "dose_era",
    domain: "Drug",
    columns: [
      { name: "dose_era_id", type: "integer", required: true, description: "" },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "drug_concept_id", type: "integer", required: true, description: "The Concept Id representing the specific drug ingredient." },
      { name: "unit_concept_id", type: "integer", required: true, description: "The Concept Id representing the unit of the specific drug ingredient." },
      { name: "dose_value", type: "float", required: true, description: "The numeric value of the dosage of the drug_ingredient." },
      { name: "dose_era_start_date", type: "datetime", required: true, description: "The date the Person started on the specific dosage, with at least 31 days since any prior exposure." },
      { name: "dose_era_end_date", type: "datetime", required: true, description: "The date the Person was no longer exposed to the dosage of the specific drug ingredient. An era is ended if there are 31 days or more between dosage records." },
    ],
  },
  {
    name: "condition_era",
    domain: "Condition",
    columns: [
      { name: "condition_era_id", type: "integer", required: true, description: "" },
      { name: "person_id", type: "integer", required: true, description: "" },
      { name: "condition_concept_id", type: "integer", required: true, description: "The Concept Id representing the Condition." },
      { name: "condition_era_start_date", type: "datetime", required: true, description: "The start date for the Condition Era constructed from the individual instances of Condition Occurrences. It is the start date of the very first chronologically recorded instance of the condition with at least 31 days since any prior record of the same Condition." },
      { name: "condition_era_end_date", type: "datetime", required: true, description: "The end date for the Condition Era constructed from the individual instances of Condition Occurrences. It is the end date of the final continuously recorded instance of the Condition." },
      { name: "condition_occurrence_count", type: "integer", required: false, description: "The number of individual Condition Occurrences used to construct the condition era." },
    ],
  },
  {
    name: "episode",
    domain: "Other",
    columns: [
      { name: "episode_id", type: "integer", required: true, description: "A unique identifier for each Episode." },
      { name: "person_id", type: "integer", required: true, description: "The PERSON_ID of the PERSON for whom the episode is recorded." },
      { name: "episode_concept_id", type: "integer", required: true, description: "The EPISODE_CONCEPT_ID represents the kind abstraction related to the disease phase, outcome or treatment." },
      { name: "episode_start_date", type: "date", required: true, description: "The date when the Episode beings." },
      { name: "episode_start_datetime", type: "datetime", required: false, description: "The date and time when the Episode begins." },
      { name: "episode_end_date", type: "date", required: false, description: "The date when the instance of the Episode is considered to have ended." },
      { name: "episode_end_datetime", type: "datetime", required: false, description: "The date when the instance of the Episode is considered to have ended." },
      { name: "episode_parent_id", type: "integer", required: false, description: "Use this field to find the Episode that subsumes the given Episode record. This is used in the case that an Episode are nested into each other." },
      { name: "episode_number", type: "integer", required: false, description: "For sequences of episodes, this is used to indicate the order the episodes occurred. For example, lines of treatment could be indicated here." },
      { name: "episode_object_concept_id", type: "integer", required: true, description: "A Standard Concept representing the disease phase, outcome, or other abstraction of which the episode consists.  For example, if the EPISODE_CONCEPT_ID is [treatment regimen](https://athena.ohdsi.org/search-terms/terms/32531) then the EPISODE_OBJECT_CONCEPT_ID should contain the chemotherapy regi..." },
      { name: "episode_type_concept_id", type: "integer", required: true, description: "This field can be used to determine the provenance of the Episode record, as in whether the episode was from an EHR system, insurance claim, registry, or other sources." },
      { name: "episode_source_value", type: "varchar", required: false, description: "The source code for the Episdoe as it appears in the source data. This code is mapped to a Standard Condition Concept in the Standardized Vocabularies and the original code is stored here for reference." },
      { name: "episode_source_concept_id", type: "integer", required: false, description: "A foreign key to a Episode Concept that refers to the code used in the source." },
    ],
  },
  {
    name: "episode_event",
    domain: "Other",
    columns: [
      { name: "episode_id", type: "integer", required: true, description: "Use this field to link the EPISODE_EVENT record to its EPISODE." },
      { name: "event_id", type: "integer", required: true, description: "This field is the primary key of the linked record in the database. For example, if the Episode Event is a Condition Occurrence, then the CONDITION_OCCURRENCE_ID of the linked record goes in this field." },
      { name: "episode_event_field_concept_id", type: "integer", required: true, description: "This field is the CONCEPT_ID that identifies which table the primary key of the linked record came from." },
    ],
  },
  {
    name: "metadata",
    domain: "Other",
    columns: [
      { name: "metadata_id", type: "integer", required: true, description: "The unique key given to a Metadata record." },
      { name: "metadata_concept_id", type: "integer", required: true, description: "" },
      { name: "metadata_type_concept_id", type: "integer", required: true, description: "" },
      { name: "name", type: "varchar", required: true, description: "" },
      { name: "value_as_string", type: "varchar", required: false, description: "" },
      { name: "value_as_concept_id", type: "integer", required: false, description: "" },
      { name: "value_as_number", type: "float", required: false, description: "This is the numerical value of the result of the Metadata, if applicable and available. It is not expected that all Metadata will have numeric results, rather, this field is here to house values should they exist." },
      { name: "metadata_date", type: "date", required: false, description: "" },
      { name: "metadata_datetime", type: "datetime", required: false, description: "" },
    ],
  },
  {
    name: "cdm_source",
    domain: "Other",
    columns: [
      { name: "cdm_source_name", type: "varchar", required: true, description: "The name of the CDM instance." },
      { name: "cdm_source_abbreviation", type: "varchar", required: true, description: "The abbreviation of the CDM instance." },
      { name: "cdm_holder", type: "varchar", required: true, description: "The holder of the CDM instance." },
      { name: "source_description", type: "varchar", required: false, description: "The description of the CDM instance." },
      { name: "source_documentation_reference", type: "varchar", required: false, description: "" },
      { name: "cdm_etl_reference", type: "varchar", required: false, description: "Put the link to the CDM version used." },
      { name: "source_release_date", type: "date", required: true, description: "The release date of the source data." },
      { name: "cdm_release_date", type: "date", required: true, description: "The release data of the CDM instance." },
      { name: "cdm_version", type: "varchar", required: false, description: "" },
      { name: "cdm_version_concept_id", type: "integer", required: true, description: "The Concept Id representing the version of the CDM." },
      { name: "vocabulary_version", type: "varchar", required: true, description: "" },
    ],
  },
  {
    name: "concept",
    domain: "Vocabulary",
    columns: [
      { name: "concept_id", type: "integer", required: true, description: "A unique identifier for each Concept across all domains." },
      { name: "concept_name", type: "varchar", required: true, description: "An unambiguous, meaningful and descriptive name for the Concept." },
      { name: "domain_id", type: "varchar", required: true, description: "A foreign key to the [DOMAIN](https://ohdsi.github.io/CommonDataModel/cdm531.html#domain) table the Concept belongs to." },
      { name: "vocabulary_id", type: "varchar", required: true, description: "A foreign key to the [VOCABULARY](https://ohdsi.github.io/CommonDataModel/cdm531.html#vocabulary) table indicating from which source the Concept has been adapted." },
      { name: "concept_class_id", type: "varchar", required: true, description: "The attribute or concept class of the Concept. Examples are 'Clinical Drug', 'Ingredient', 'Clinical Finding' etc." },
      { name: "standard_concept", type: "varchar", required: false, description: "This flag determines where a Concept is a Standard Concept, i.e. is used in the data, a Classification Concept, or a non-standard Source Concept. The allowable values are 'S' (Standard Concept) and 'C' (Classification Concept), otherwise the content is NULL." },
      { name: "concept_code", type: "varchar", required: true, description: "The concept code represents the identifier of the Concept in the source vocabulary, such as SNOMED-CT concept IDs, RxNorm RXCUIs etc. Note that concept codes are not unique across vocabularies." },
      { name: "valid_start_date", type: "date", required: true, description: "The date when the Concept was first recorded. The default value is 1-Jan-1970, meaning, the Concept has no (known) date of inception." },
      { name: "valid_end_date", type: "date", required: true, description: "The date when the Concept became invalid because it was deleted or superseded (updated) by a new concept. The default value is 31-Dec-2099, meaning, the Concept is valid until it becomes deprecated." },
      { name: "invalid_reason", type: "varchar", required: false, description: "Reason the Concept was invalidated. Possible values are D (deleted), U (replaced with an update) or NULL when valid_end_date has the default value." },
    ],
  },
  {
    name: "vocabulary",
    domain: "Vocabulary",
    columns: [
      { name: "vocabulary_id", type: "varchar", required: true, description: "A unique identifier for each Vocabulary, such as ICD9CM, SNOMED, Visit." },
      { name: "vocabulary_name", type: "varchar", required: true, description: "The name describing the vocabulary, for example, International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS) etc." },
      { name: "vocabulary_reference", type: "varchar", required: false, description: "External reference to documentation or available download of the about the vocabulary." },
      { name: "vocabulary_version", type: "varchar", required: false, description: "Version of the Vocabulary as indicated in the source." },
      { name: "vocabulary_concept_id", type: "integer", required: true, description: "A Concept that represents the Vocabulary the VOCABULARY record belongs to." },
    ],
  },
  {
    name: "domain",
    domain: "Vocabulary",
    columns: [
      { name: "domain_id", type: "varchar", required: true, description: "A unique key for each domain." },
      { name: "domain_name", type: "varchar", required: true, description: "The name describing the Domain, e.g. Condition, Procedure, Measurement etc." },
      { name: "domain_concept_id", type: "integer", required: true, description: "A Concept representing the Domain Concept the DOMAIN record belongs to." },
    ],
  },
  {
    name: "concept_class",
    domain: "Vocabulary",
    columns: [
      { name: "concept_class_id", type: "varchar", required: true, description: "A unique key for each class." },
      { name: "concept_class_name", type: "varchar", required: true, description: "The name describing the Concept Class, e.g. Clinical Finding, Ingredient, etc." },
      { name: "concept_class_concept_id", type: "integer", required: true, description: "A Concept that represents the Concept Class." },
    ],
  },
  {
    name: "concept_relationship",
    domain: "Vocabulary",
    columns: [
      { name: "concept_id_1", type: "integer", required: true, description: "" },
      { name: "concept_id_2", type: "integer", required: true, description: "" },
      { name: "relationship_id", type: "varchar", required: true, description: "The relationship between CONCEPT_ID_1 and CONCEPT_ID_2. Please see the [Vocabulary Conventions](https://ohdsi.github.io/CommonDataModel/dataModelConventions.html#concept_relationships). for more information." },
      { name: "valid_start_date", type: "date", required: true, description: "The date when the relationship is first recorded." },
      { name: "valid_end_date", type: "date", required: true, description: "The date when the relationship is invalidated." },
      { name: "invalid_reason", type: "varchar", required: false, description: "Reason the relationship was invalidated. Possible values are 'D' (deleted), 'U' (updated) or NULL." },
    ],
  },
  {
    name: "relationship",
    domain: "Vocabulary",
    columns: [
      { name: "relationship_id", type: "varchar", required: true, description: "The type of relationship captured by the relationship record." },
      { name: "relationship_name", type: "varchar", required: true, description: "" },
      { name: "is_hierarchical", type: "varchar", required: true, description: "Defines whether a relationship defines concepts into classes or hierarchies. Values are 1 for hierarchical relationship or 0 if not." },
      { name: "defines_ancestry", type: "varchar", required: true, description: "Defines whether a hierarchical relationship contributes to the concept_ancestor table. These are subsets of the hierarchical relationships. Valid values are 1 or 0." },
      { name: "reverse_relationship_id", type: "varchar", required: true, description: "The identifier for the relationship used to define the reverse relationship between two concepts." },
      { name: "relationship_concept_id", type: "integer", required: true, description: "A foreign key that refers to an identifier in the [CONCEPT](https://ohdsi.github.io/CommonDataModel/cdm531.html#concept) table for the unique relationship concept." },
    ],
  },
  {
    name: "concept_synonym",
    domain: "Vocabulary",
    columns: [
      { name: "concept_id", type: "integer", required: true, description: "" },
      { name: "concept_synonym_name", type: "varchar", required: true, description: "" },
      { name: "language_concept_id", type: "integer", required: true, description: "" },
    ],
  },
  {
    name: "concept_ancestor",
    domain: "Vocabulary",
    columns: [
      { name: "ancestor_concept_id", type: "integer", required: true, description: "The Concept Id for the higher-level concept that forms the ancestor in the relationship." },
      { name: "descendant_concept_id", type: "integer", required: true, description: "The Concept Id for the lower-level concept that forms the descendant in the relationship." },
      { name: "min_levels_of_separation", type: "integer", required: true, description: "The minimum separation in number of levels of hierarchy between ancestor and descendant concepts. This is an attribute that is used to simplify hierarchic analysis." },
      { name: "max_levels_of_separation", type: "integer", required: true, description: "The maximum separation in number of levels of hierarchy between ancestor and descendant concepts. This is an attribute that is used to simplify hierarchic analysis." },
    ],
  },
  {
    name: "source_to_concept_map",
    domain: "Other",
    columns: [
      { name: "source_code", type: "varchar", required: true, description: "The source code being translated into a Standard Concept." },
      { name: "source_concept_id", type: "integer", required: true, description: "A foreign key to the Source Concept that is being translated into a Standard Concept." },
      { name: "source_vocabulary_id", type: "varchar", required: true, description: "A foreign key to the VOCABULARY table defining the vocabulary of the source code that is being translated to a Standard Concept." },
      { name: "source_code_description", type: "varchar", required: false, description: "An optional description for the source code. This is included as a convenience to compare the description of the source code to the name of the concept." },
      { name: "target_concept_id", type: "integer", required: true, description: "The target Concept to which the source code is being mapped." },
      { name: "target_vocabulary_id", type: "varchar", required: true, description: "The Vocabulary of the target Concept." },
      { name: "valid_start_date", type: "date", required: true, description: "The date when the mapping instance was first recorded." },
      { name: "valid_end_date", type: "date", required: true, description: "The date when the mapping instance became invalid because it was deleted or superseded (updated) by a new relationship. Default value is 31-Dec-2099." },
      { name: "invalid_reason", type: "varchar", required: false, description: "Reason the mapping instance was invalidated. Possible values are D (deleted), U (replaced with an update) or NULL when valid_end_date has the default value." },
    ],
  },
  {
    name: "drug_strength",
    domain: "Drug",
    columns: [
      { name: "drug_concept_id", type: "integer", required: true, description: "The Concept representing the Branded Drug or Clinical Drug Product." },
      { name: "ingredient_concept_id", type: "integer", required: true, description: "The Concept representing the active ingredient contained within the drug product." },
      { name: "amount_value", type: "float", required: false, description: "The numeric value or the amount of active ingredient contained within the drug product." },
      { name: "amount_unit_concept_id", type: "integer", required: false, description: "The Concept representing the Unit of measure for the amount of active ingredient contained within the drug product." },
      { name: "numerator_value", type: "float", required: false, description: "The concentration of the active ingredient contained within the drug product." },
      { name: "numerator_unit_concept_id", type: "integer", required: false, description: "The Concept representing the Unit of measure for the concentration of active ingredient." },
      { name: "denominator_value", type: "float", required: false, description: "The amount of total liquid (or other divisible product, such as ointment, gel, spray, etc.)." },
      { name: "denominator_unit_concept_id", type: "integer", required: false, description: "The Concept representing the denominator unit for the concentration of active ingredient." },
      { name: "box_size", type: "integer", required: false, description: "The number of units of Clinical Branded Drug or Quantified Clinical or Branded Drug contained in a box as dispensed to the patient." },
      { name: "valid_start_date", type: "date", required: true, description: "The date when the Concept was first recorded. The default value is 1-Jan-1970." },
      { name: "valid_end_date", type: "date", required: true, description: "The date when then Concept became invalid." },
      { name: "invalid_reason", type: "varchar", required: false, description: "Reason the concept was invalidated. Possible values are D (deleted), U (replaced with an update) or NULL when valid_end_date has the default value." },
    ],
  },
  {
    name: "cohort",
    domain: "Cohort",
    columns: [
      { name: "cohort_definition_id", type: "integer", required: true, description: "" },
      { name: "subject_id", type: "integer", required: true, description: "" },
      { name: "cohort_start_date", type: "date", required: true, description: "" },
      { name: "cohort_end_date", type: "date", required: true, description: "" },
    ],
  },
  {
    name: "cohort_definition",
    domain: "Cohort",
    columns: [
      { name: "cohort_definition_id", type: "integer", required: true, description: "This is the identifier given to the cohort, usually by the ATLAS application" },
      { name: "cohort_definition_name", type: "varchar", required: true, description: "A short description of the cohort" },
      { name: "cohort_definition_description", type: "varchar", required: false, description: "A complete description of the cohort." },
      { name: "definition_type_concept_id", type: "integer", required: true, description: "Type defining what kind of Cohort Definition the record represents and how the syntax may be executed." },
      { name: "cohort_definition_syntax", type: "varchar", required: false, description: "Syntax or code to operationalize the Cohort Definition." },
      { name: "subject_concept_id", type: "integer", required: true, description: "This field contains a Concept that represents the domain of the subjects that are members of the cohort (e.g., Person, Provider, Visit)." },
      { name: "cohort_initiation_date", type: "date", required: false, description: "A date to indicate when the Cohort was initiated in the COHORT table." },
    ],
  },
];
