"""Phase 2 — Configuration wizard.

Collects user preferences via questionary prompts, then writes:
  .env             (repo root — Docker Compose env vars)
  backend/.env     (Laravel app env vars)

Also saves generated credentials to .install-credentials (gitignored).
"""
from __future__ import annotations

import json
import secrets
import string
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from . import utils

console = Console()
REPO_ROOT = utils.REPO_ROOT


def _generate_password(length: int = 24) -> str:
    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _extract_host(url: str) -> str:
    """Extract hostname from a URL string."""
    try:
        from urllib.parse import urlparse
        return urlparse(url).hostname or "localhost"
    except Exception:
        return "localhost"


def _build_sanctum_domains(app_url: str) -> str:
    host = _extract_host(app_url)
    domains = {"localhost", "localhost:80", "localhost:5173", "localhost:8082"}
    if host not in ("localhost", "127.0.0.1"):
        domains.add(host)
    return ",".join(sorted(domains))


def _session_domain(app_url: str) -> str:
    host = _extract_host(app_url)
    if host in ("localhost", "127.0.0.1"):
        return "null"
    return host


def collect(resume_data: dict[str, Any] | None = None) -> dict[str, Any]:
    """Run the interactive config wizard. Returns a config dict."""
    import questionary

    console.rule("[bold]Phase 2 — Configuration[/bold]")
    console.print("Answer the prompts below. Press [Enter] to accept defaults.\n")

    defaults = resume_data or {}

    app_url = questionary.text(
        "App URL",
        default=defaults.get("app_url", "http://localhost"),
    ).ask()

    env = questionary.select(
        "Environment",
        choices=["local", "production"],
        default=defaults.get("env", "local"),
    ).ask()

    db_password = defaults.get("db_password") or _generate_password(24)
    use_generated_db = questionary.confirm(
        f"Use auto-generated DB password ({db_password[:6]}…)?",
        default=True,
    ).ask()
    if not use_generated_db:
        db_password = questionary.password("DB password").ask()

    admin_email = questionary.text(
        "Admin email",
        default=defaults.get("admin_email", "admin@example.com"),
    ).ask()

    admin_name = questionary.text(
        "Admin name",
        default=defaults.get("admin_name", "Admin"),
    ).ask()

    admin_password = defaults.get("admin_password") or _generate_password(16)
    use_generated_admin_pw = questionary.confirm(
        f"Use auto-generated admin password ({admin_password[:4]}…)?",
        default=True,
    ).ask()
    if not use_generated_admin_pw:
        admin_password = questionary.password("Admin password (min 8 chars)").ask()

    timezone = questionary.text(
        "Timezone",
        default=defaults.get("timezone", "UTC"),
    ).ask()

    include_eunomia = questionary.confirm(
        "Load Eunomia GiBleed demo dataset? (Recommended — adds sample CDM data)",
        default=True,
    ).ask()

    ollama_url = questionary.text(
        "Ollama base URL (leave blank to skip AI features)",
        default=defaults.get("ollama_url", "http://host.docker.internal:11434"),
    ).ask()

    show_advanced = questionary.confirm("Configure advanced port settings?", default=False).ask()

    nginx_port = 8082
    postgres_port = 5480
    redis_port = 6381
    ai_port = 8002

    if show_advanced:
        nginx_port    = int(questionary.text("NGINX_PORT",    default=str(nginx_port)).ask())
        postgres_port = int(questionary.text("POSTGRES_PORT", default=str(postgres_port)).ask())
        redis_port    = int(questionary.text("REDIS_PORT",    default=str(redis_port)).ask())
        ai_port       = int(questionary.text("AI_PORT",       default=str(ai_port)).ask())

    return {
        "app_url":        app_url,
        "env":            env,
        "db_password":    db_password,
        "admin_email":    admin_email,
        "admin_name":     admin_name,
        "admin_password": admin_password,
        "timezone":       timezone,
        "include_eunomia": include_eunomia,
        "ollama_url":     ollama_url,
        "nginx_port":     nginx_port,
        "postgres_port":  postgres_port,
        "redis_port":     redis_port,
        "ai_port":        ai_port,
    }


def build_root_env(cfg: dict[str, Any]) -> str:
    return (
        f"# Parthenon — generated by installer\n"
        f"APP_ENV={cfg['env']}\n"
        f"DB_PASSWORD={cfg['db_password']}\n"
        f"\n"
        f"# Host port mapping\n"
        f"NGINX_PORT={cfg['nginx_port']}\n"
        f"VITE_PORT=5175\n"
        f"POSTGRES_PORT={cfg['postgres_port']}\n"
        f"REDIS_PORT={cfg['redis_port']}\n"
        f"AI_PORT={cfg['ai_port']}\n"
        f"\n"
        f"# Ollama\n"
        f"OLLAMA_BASE_URL={cfg['ollama_url'] or 'http://host.docker.internal:11434'}\n"
        f"OLLAMA_MODEL=MedAIBase/MedGemma1.5:4b\n"
    )


def build_backend_env(cfg: dict[str, Any]) -> str:
    is_prod = cfg["env"] == "production"
    session_domain = _session_domain(cfg["app_url"])
    sanctum_domains = _build_sanctum_domains(cfg["app_url"])

    return (
        f"APP_NAME=Parthenon\n"
        f"APP_ENV={cfg['env']}\n"
        f"APP_KEY=\n"
        f"APP_DEBUG={'false' if is_prod else 'true'}\n"
        f"APP_TIMEZONE={cfg['timezone']}\n"
        f"APP_URL={cfg['app_url']}\n"
        f"APP_VERSION=0.1.0\n"
        f"\n"
        f"APP_LOCALE=en\n"
        f"APP_FALLBACK_LOCALE=en\n"
        f"APP_FAKER_LOCALE=en_US\n"
        f"APP_MAINTENANCE_DRIVER=file\n"
        f"BCRYPT_ROUNDS=12\n"
        f"\n"
        f"LOG_CHANNEL=stack\n"
        f"LOG_STACK=single\n"
        f"LOG_DEPRECATIONS_CHANNEL=null\n"
        f"LOG_LEVEL={'warning' if is_prod else 'debug'}\n"
        f"\n"
        f"# Primary connection (app tables — Docker postgres)\n"
        f"DB_CONNECTION=pgsql\n"
        f"DB_HOST=postgres\n"
        f"DB_PORT=5432\n"
        f"DB_DATABASE=parthenon\n"
        f"DB_USERNAME=parthenon\n"
        f"DB_PASSWORD={cfg['db_password']}\n"
        f"DB_SEARCH_PATH=app,public\n"
        f"\n"
        f"# CDM / Vocabulary / Results — same Docker postgres, eunomia schema\n"
        f"CDM_DB_SEARCH_PATH=eunomia,public\n"
        f"VOCAB_DB_SEARCH_PATH=eunomia,public\n"
        f"RESULTS_DB_SEARCH_PATH=achilles_results,public\n"
        f"\n"
        f"SESSION_DRIVER=redis\n"
        f"SESSION_LIFETIME=120\n"
        f"SESSION_ENCRYPT=false\n"
        f"SESSION_PATH=/\n"
        f"SESSION_DOMAIN={session_domain}\n"
        f"\n"
        f"BROADCAST_CONNECTION=redis\n"
        f"FILESYSTEM_DISK=local\n"
        f"QUEUE_CONNECTION=redis\n"
        f"\n"
        f"CACHE_STORE=redis\n"
        f"CACHE_PREFIX=parthenon_\n"
        f"\n"
        f"REDIS_CLIENT=phpredis\n"
        f"REDIS_HOST=redis\n"
        f"REDIS_PASSWORD=null\n"
        f"REDIS_PORT=6379\n"
        f"\n"
        f"SANCTUM_STATEFUL_DOMAINS={sanctum_domains}\n"
        f"\n"
        f"AI_SERVICE_URL=http://python-ai:8000\n"
        f"R_SERVICE_URL=http://r-runtime:8787\n"
        f"\n"
        f"HORIZON_DASHBOARD_ENABLED=true\n"
        f"\n"
        f"MAIL_MAILER=log\n"
        f"RESEND_API_KEY=\n"
        f"MAIL_FROM_ADDRESS=noreply@parthenon.local\n"
        f'MAIL_FROM_NAME="${{APP_NAME}}"\n'
        f"\n"
        f'VITE_APP_NAME="${{APP_NAME}}"\n'
    )


def _show_diff(path: Path, content: str) -> None:
    console.print(f"\n[bold cyan]{path}[/bold cyan]")
    syntax = Syntax(content, "ini", theme="monokai", line_numbers=False)
    console.print(Panel(syntax, expand=False))


def write(cfg: dict[str, Any]) -> None:
    """Write .env and backend/.env after showing a preview."""
    root_env = build_root_env(cfg)
    backend_env = build_backend_env(cfg)

    console.print("\n[bold]Configuration preview:[/bold]")
    _show_diff(REPO_ROOT / ".env", root_env)
    _show_diff(REPO_ROOT / "backend" / ".env", backend_env)

    import questionary
    ok = questionary.confirm("Write these files?", default=True).ask()
    if not ok:
        console.print("[yellow]Aborted. No files written.[/yellow]")
        raise SystemExit(0)

    (REPO_ROOT / ".env").write_text(root_env)
    (REPO_ROOT / "backend" / ".env").write_text(backend_env)

    # Save credentials
    creds_path = REPO_ROOT / ".install-credentials"
    creds = {
        "app_url":        cfg["app_url"],
        "admin_email":    cfg["admin_email"],
        "admin_password": cfg["admin_password"],
        "db_password":    cfg["db_password"],
    }
    creds_path.write_text(json.dumps(creds, indent=2))
    creds_path.chmod(0o600)

    console.print(f"[green]✓ Credentials saved to {creds_path.name}[/green]")
    console.print("[green]✓ .env files written.[/green]\n")
